### PR TITLE
Keep models loaded in RAM - FOR TESTING - NO MERGE

### PR DESCRIPTION
**Pull request by Slider0007**
Approach to load tflite models only once from SD and keep them in RAM - ONLY TECDEMO

`Models` loaded during init and kept in RAM (no reload in each round)

Actual problems to solve:
- Cam image is in JPG format and needs to be converted to matrix image (STBI lib is used for this, stbi_load_from_memory function). This function needs helper structures to convert. Those helper structure are also dynamically allocated in PSRAM before the actual resulting image is saved to PSRAM. The helper structures get freed after process is finished. This creates a gap in PSRAM memory map.
- In take image step there is only memory left model in sum of 1MB (to less for the model we have) due to the memory gap and preallocation approach

Goals to have enough memory the keep models > 1MB in RAM:
- No need of any prealocation to have enough memory in take image step (avoid fragmention in general, situation like we have in 15.1.1 is sufficient)
- Remove of zwImage --> reuse of rawimage
- Avoid the memory gap of STBI lib --> STBI lib needs to be patched

Excel - Drawings memory usage:
[PSRAM - Memory usage.xlsx](https://github.com/jomjol/AI-on-the-edge-device/files/11132026/PSRAM.-.Memory.usage.xlsx)

### Visu with memory gap (STBI lib not modified):
image

---
### Proof of Work with largest models (1,2MB + ca. 200kb) - STBI lib modified
image

```
I (257086) TFLITE SERVER: Round #3 started
I (258336) C IMG BASIS: LoadFromMemory
I (259156) C IMG BASIS: Image loaded from memory: 640, 480, 3
I (342926) POSTPROC: main: Raw: 0530.87470, Value: 530.87470, Status: no error
I (343616) TFLITE SERVER: Round #3 completed (86 seconds)
I (377126) TFLITE SERVER: Round #4 started
I (378376) C IMG BASIS: LoadFromMemory
I (379186) C IMG BASIS: Image loaded from memory: 640, 480, 3
E (462926) POSTPROC: main: Raw: 0530.82253, Value: , Status: Neg. Rate - Read:  - Raw: 0530.82253 - Pre: 530.87470
I (463486) TFLITE SERVER: Round #4 completed (86 seconds)

Showing data for heap: 0x3f800000
Block 0x3f80086c data, size: 40 bytes, Free: No
Block 0x3f800898 data, size: 20 bytes, Free: No
Block 0x3f8008b0 data, size: 61440 bytes, Free: No
Block 0x3f80f8b4 data, size: 55880 bytes, Free: No
Block 0x3f81d300 data, size: 30000 bytes, Free: No
Block 0x3f824834 data, size: 921604 bytes, Free: No
Block 0x3f90583c data, size: 128004 bytes, Free: No
Block 0x3f924c44 data, size: 1200956 bytes, Free: No
**Block 0x3fa49f84 data, size: 29312 bytes, Free: Yes**
Block 0x3fa51208 data, size: 1920 bytes, Free: No
Block 0x3fa5198c data, size: 10292 bytes, Free: No
Block 0x3fa541c4 data, size: 1920 bytes, Free: No
Block 0x3fa54948 data, size: 10292 bytes, Free: No
Block 0x3fa57180 data, size: 1920 bytes, Free: No
Block 0x3fa57904 data, size: 10292 bytes, Free: No
Block 0x3fa5a13c data, size: 1920 bytes, Free: No
Block 0x3fa5a8c0 data, size: 10292 bytes, Free: No
Block 0x3fa5d0f8 data, size: 183756 bytes, Free: No
Block 0x3fa89ec8 data, size: 3072 bytes, Free: No
Block 0x3fa8aacc data, size: 50700 bytes, Free: No
Block 0x3fa970dc data, size: 3072 bytes, Free: No
Block 0x3fa97ce0 data, size: 50700 bytes, Free: No
Block 0x3faa42f0 data, size: 3072 bytes, Free: No
Block 0x3faa4ef4 data, size: 50700 bytes, Free: No
Block 0x3fab1504 data, size: 3072 bytes, Free: No
Block 0x3fab2108 data, size: 50700 bytes, Free: No
Block 0x3fabe718 data, size: 921600 bytes, Free: No
Block 0x3fb9f71c data, size: 20596 bytes, Free: No
**Block 0x3fba4794 data, size: 374884 bytes, Free: Yes**
```

------
## Backup info
My analysis from last week (mentioned already here: https://github.com/jomjol/AI-on-the-edge-device/pull/2215#issuecomment-1480121093)
Slider0007 approach: Keep models loaded, share tensor/ImageTMP
I did also some research to this topic. Approach is working till sum of 1000kB models (model1+2), then it also hangs at the same point than in approach from @caco3. This means 1200kB models are not working with this approach anymore. More detailed infos to further findings I have described in private chat.

image

###Output of PSRAM memory blocks after a few rounds (flow finished):
```
Showing data for heap: 0x3f802c70
Block 0x3f8034dc data, size: 40 bytes, Free: No
Block 0x3f803508 data, size: 20 bytes, Free: No
Block 0x3f803520 data, size: 61440 bytes, Free: No
Block 0x3f812524 data, size: 55880 bytes, Free: No
Block 0x3f81ff70 data, size: 80 bytes, Free: No
Block 0x3f81ffc4 data, size: 16 bytes, Free: No
Block 0x3f81ffd8 data, size: 16 bytes, Free: No
Block 0x3f81ffec data, size: 16 bytes, Free: No
Block 0x3f820000 data, size: 16 bytes, Free: No
Block 0x3f820014 data, size: 16 bytes, Free: No
Block 0x3f820028 data, size: 16 bytes, Free: No
Block 0x3f82003c data, size: 16 bytes, Free: No
Block 0x3f820050 data, size: 16 bytes, Free: No
Block 0x3f820064 data, size: 12 bytes, Free: No
Block 0x3f820074 data, size: 24 bytes, Free: No
Block 0x3f820090 data, size: 2080 bytes, Free: No
Block 0x3f8208b4 data, size: 136 bytes, Free: No
Block 0x3f820940 data, size: 136 bytes, Free: No
Block 0x3f8209cc data, size: 1696 bytes, Free: No
Block 0x3f821070 data, size: 1696 bytes, Free: No
Block 0x3f821714 data, size: 1696 bytes, Free: No
Block 0x3f821db8 data, size: 1696 bytes, Free: No
Block 0x3f82245c data, size: 1696 bytes, Free: No
Block 0x3f822b00 data, size: 1696 bytes, Free: No
Block 0x3f8231a4 data, size: 1696 bytes, Free: No
Block 0x3f823848 data, size: 1696 bytes, Free: No
Block 0x3f823eec data, size: 1696 bytes, Free: No
Block 0x3f824590 data, size: 1696 bytes, Free: No
Block 0x3f824c34 data, size: 1696 bytes, Free: No
Block 0x3f8252d8 data, size: 1696 bytes, Free: No
Block 0x3f82597c data, size: 1696 bytes, Free: No
Block 0x3f826020 data, size: 1696 bytes, Free: No
Block 0x3f8266c4 data, size: 1696 bytes, Free: No
Block 0x3f826d68 data, size: 1696 bytes, Free: No
Block 0x3f82740c data, size: 552 bytes, Free: No
Block 0x3f827638 data, size: 768 bytes, Free: No
Block 0x3f82793c data, size: 56 bytes, Free: No
Block 0x3f827978 data, size: 12 bytes, Free: No
Block 0x3f827988 data, size: 12 bytes, Free: No
Block 0x3f827998 data, size: 56 bytes, Free: No
Block 0x3f8279d4 data, size: 12 bytes, Free: No
Block 0x3f8279e4 data, size: 80 bytes, Free: No
Block 0x3f827a38 data, size: 12 bytes, Free: No
Block 0x3f827a48 data, size: 12 bytes, Free: No
Block 0x3f827a58 data, size: 16 bytes, Free: No
Block 0x3f827a6c data, size: 76 bytes, Free: No
Block 0x3f827abc data, size: 56 bytes, Free: No
Block 0x3f827af8 data, size: 80 bytes, Free: No
Block 0x3f827b4c data, size: 184 bytes, Free: No
Block 0x3f827c08 data, size: 184 bytes, Free: No
Block 0x3f827cc4 data, size: 80 bytes, Free: No
Block 0x3f827d18 data, size: 40 bytes, Free: No
Block 0x3f827d44 data, size: 64 bytes, Free: No
Block 0x3f827d88 data, size: 104 bytes, Free: No
Block 0x3f827df4 data, size: 16 bytes, Free: No
Block 0x3f827e08 data, size: 16 bytes, Free: No
Block 0x3f827e1c data, size: 12 bytes, Free: Yes
Block 0x3f827e2c data, size: 44 bytes, Free: No
Block 0x3f827e5c data, size: 108 bytes, Free: Yes
Block 0x3f827ecc data, size: 56 bytes, Free: No
Block 0x3f827f08 data, size: 208 bytes, Free: No
Block 0x3f827fdc data, size: 208 bytes, Free: No
Block 0x3f8280b0 data, size: 16 bytes, Free: No
Block 0x3f8280c4 data, size: 120 bytes, Free: No
Block 0x3f828140 data, size: 64 bytes, Free: No
Block 0x3f828184 data, size: 104 bytes, Free: Yes
Block 0x3f8281f0 data, size: 136 bytes, Free: No
Block 0x3f82827c data, size: 942080 bytes, Free: No
Block 0x3f90e280 data, size: 128004 bytes, Free: No
Block 0x3f92d688 data, size: 226480 bytes, Free: No
Block 0x3f964b3c data, size: 1920 bytes, Free: No
Block 0x3f9652c0 data, size: 4860 bytes, Free: No
Block 0x3f9665c0 data, size: 1920 bytes, Free: No
Block 0x3f966d44 data, size: 4860 bytes, Free: No
Block 0x3f968044 data, size: 1920 bytes, Free: No
Block 0x3f9687c8 data, size: 4860 bytes, Free: No
Block 0x3f969ac8 data, size: 183756 bytes, Free: No
Block 0x3f996898 data, size: 3072 bytes, Free: No
Block 0x3f99749c data, size: 17788 bytes, Free: No
Block 0x3f99ba1c data, size: 3072 bytes, Free: No
Block 0x3f99c620 data, size: 17788 bytes, Free: No
Block 0x3f9a0ba0 data, size: 3072 bytes, Free: No
Block 0x3f9a17a4 data, size: 17788 bytes, Free: No
Block 0x3f9a5d24 data, size: 3072 bytes, Free: No
Block 0x3f9a6928 data, size: 17788 bytes, Free: No
Block 0x3f9aaea8 data, size: 3072 bytes, Free: No
----> same start block like below
Block 0x3f9abaac data, size: 17788 bytes, Free: No
Block 0x3f9b002c data, size: 856 bytes, Free: Yes
Block 0x3f9b0388 data, size: 56 bytes, Free: No
Block 0x3f9b03c4 data, size: 12 bytes, Free: No
Block 0x3f9b03d4 data, size: 512 bytes, Free: No

---> Helper structure memory
Block 0x3f9b05d8 data, size: 632400 bytes, Free: Yes --> only remaining not solved bigger fragmentation; potentially internal CImage helper structure which is neccessary to convert JPG to matrix image
<--- Helper structure memory

Block 0x3fa4ac2c data, size: 921604 bytes, Free: No
Block 0x3fb2bc34 data, size: 869316 bytes, Free: Yes

During Take image state in the following round (marked CImage Helper strucutre block):
----> same start block like above
Block 0x3f9abaac data, size: 17788 bytes, Free: No
Block 0x3f9b002c data, size: 208 bytes, Free: No
Block 0x3f9b0100 data, size: 208 bytes, Free: No
Block 0x3f9b01d4 data, size: 104 bytes, Free: Yes
Block 0x3f9b0240 data, size: 56 bytes, Free: No
Block 0x3f9b027c data, size: 264 bytes, Free: Yes
Block 0x3f9b0388 data, size: 56 bytes, Free: No
Block 0x3f9b03c4 data, size: 12 bytes, Free: No

---> Helper structure memory
Block 0x3f9b03d4 data, size: 18456 bytes, Free: No
Block 0x3f9b4bf0 data, size: 307216 bytes, Free: No
Block 0x3f9ffc04 data, size: 153616 bytes, Free: No
Block 0x3fa25418 data, size: 153616 bytes, Free: No
<--- Helper structure memory

Block 0x3fa4ac2c data, size: 921604 bytes, Free: No
Block 0x3fb2bc34 data, size: 869316 bytes, Free: Yes
```

If nothing come in between the same free blocks are allocated again, but whenever something is coming in between and take only some bytes PSRAM gets even more fragemented. That's my major concern!

### CODE REVIEW

**Comment by caco3** [comment]
Here the PSRAM consuption of 2b6c340:

`dig-class11_1600_s2.tflite` (350 KB) and `ana-cont_1105_s2_q.tflite` (52 kB)

Note that does not use the largest digi model!

grafik

**Comment by Slider0007** [comment]
> Here the PSRAM consumption of [2b6c340](https://github.com/jomjol/AI-on-the-edge-device/commit/2b6c340707a3b901b492e56a25cd386529496b19).
> 
> What I do not understand is why it crashes with the 1. MB model (bottom graphic). I also do not see the STBI allocations. Shouldn't they be visible in the top graphic (smaller model) where it works fine for several rounds?
> 
> ### `dig-class11_1600_s2.tflite` (350 KB) and `ana-cont_1105_s2_q.tflite` (52 kB)
> Note that does not use the largest digi model!
> 
> grafik
> 
> ### `dig-cont_0611_s3.tflite` (1.1 MB) and `ana-cont_1105_s2_q.tflite` (52 kB)
> crashing!
> 
> keep-model-loaded_2b6c340_dig-cont_0611_s3_crash
> 
> crash, line 1609:
> 
> ```
> I (21411) C IMG BASIS: Image loaded from memory: 640, 480, 0
> E (21411) C IMG BASIS: Failed loading image from memory into CBasisImage
> ```
> 
> [keep-model-loaded_2b6c340_dig-cont_0611_s3_crash.log](https://github.com/jomjol/AI-on-the-edge-device/files/11128973/keep-model-loaded_2b6c340_dig-cont_0611_s3_crash.log)

The reason I described already here with this graphic (also part of the one replay of the other PR):
image

**Comment by caco3** [comment]
Finally here a catch where we see that it allocates 640 KB in 3 parts and then, before freeing them again, another 920 KB.
This only works because i did not use the 1 MB model.

grafik

**Comment by Pablo2048** [comment]
Hi guys. Sorry for complete off-topic question here, but what is the tool you used to draw the memory map image from log file? Thanks...

**Comment by caco3** [comment]
> Hi guys. Sorry for complete off-topic question here, but what is the tool you used to draw the memory map image from log file? Thanks...

Its a simple python script I made for this purpose, see https://github.com/caco3/psram-usage-visualizer

**Comment by caco3** [comment]
@Slider0007 Is your modification of STBI really required? Is it not possible to interfer with the malloc/free calls as shown in https://github.com/jomjol/AI-on-the-edge-device/commit/570d220c8051237ffaccbf35ad8243b5cc2c5b72#diff-ab169791765d290f2afd8913da08ff7f3125fcc531c8e100fdd20c74679071cf ?

**Comment by Slider0007** [comment]
> @Slider0007 Is your modification of STBI really required? Is it not possible to interfer with the malloc/free calls as shown in [570d220#diff-ab169791765d290f2afd8913da08ff7f3125fcc531c8e100fdd20c74679071cf](https://github.com/jomjol/AI-on-the-edge-device/commit/570d220c8051237ffaccbf35ad8243b5cc2c5b72#diff-ab169791765d290f2afd8913da08ff7f3125fcc531c8e100fdd20c74679071cf) ?

In my opinion it not possible with the centralized approach because it's quite a special case we need.

**Comment by Slider0007** [comment]
Closing. This was only a demo.

**Pull request closed without merging**
