### PR TITLE
Add demo mode

### PR DESCRIPTION
**Pull request by caco3**
Adds a demo mode, see https://github.com/jomjol/AI-on-the-edge-device/wiki/Demo-Mode for details.

The wiki page contains an example demo file. It can be uploaded using the OTA Update functionality.
- [x] @jomjol As is now, the demo folder must exist, else the extraction will fail! Can you extend OTA to create the needed folders?
- [x] Taking the alignment creates an empty file: `␛[0;31mE (948850) C IMG BASIS: Failed to load /sdcard/img_tmp/ref0_org_org.jpg! Is it corrupted?␛[0m`. Not sure if this is not an issue of rolling...
- [x] Das Häkchen in der Config bleibt nicht gesetzt nach Neustart.
- [x] Parameter ggf. besser unter Expert?

How does it work?
The device behaves as normal.
How ever after taking a framebuffer from the camera, the framebuffer gets replaced by the image from the SD-Card.

### CODE REVIEW

**Comment by stefan123t** [comment]
@caco3 also got this `E (95242) C IMG BASIS: Failed to load /sdcard/img_tmp/ref0_org_org.jpg! Is it corrupted?` in rolling 4b23e0c

**Comment by caco3** [comment]
> @caco3 also got this `E (95242) C IMG BASIS: Failed to load /sdcard/img_tmp/ref0_org_org.jpg! Is it corrupted?` in rolling [4b23e0c](https://github.com/jomjol/AI-on-the-edge-device/commit/4b23e0c6c38cdcb3e0ddbc310780facb46a29970)

@stefan123t Thanks for confirming!
Now we have to find out in which commit it broke

**Comment by jomjol** [comment]
/sdcard/demo gets now created at the start of the main

**Comment by caco3** [comment]
> > @caco3 also got this `E (95242) C IMG BASIS: Failed to load /sdcard/img_tmp/ref0_org_org.jpg! Is it corrupted?` in rolling [4b23e0c](https://github.com/jomjol/AI-on-the-edge-device/commit/4b23e0c6c38cdcb3e0ddbc310780facb46a29970)
> 
> @stefan123t Thanks for confirming! Now we have to find out in which commit it broke

We found and fixed it, see https://github.com/jomjol/AI-on-the-edge-device/pull/1726

**Pull request merged**
