### PR TITLE
Move parameter doc to use tooltips generated using the online documentation

### PR DESCRIPTION
**Pull request by caco3**
- Replaced the parameter information with tooltips
- The tooltips get generated at build timebased on the online documentation at https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters
- Renamed most parameters (just on the HTML page)
- Tweaked config page

grafik

### CODE REVIEW

**Comment by caco3** [comment]
@Slider0007 @jomjol IMO this MR is now ready

**Comment by jomjol** [comment]
Just installed it and had a first look. Is looking good!

**Comment by Slider0007** [comment]
I also just installed and tested it. Looks really nice and streamlined. Cool feature :-)
How do you load the info? Pull it directly out of github docu repo?

Some texts needs to be slightly adpated. So the workflow is just update them in the doce repo?

**Comment by caco3** [comment]
It involves two steps.

1. Update the parameter pages in the documentation: https://github.com/jomjol/AI-on-the-edge-device-docs/tree/main/param-docs/parameter-pages
2. Rebuild the firmware. It automatically grabs the latest parameter pages from above repo (min branch). and embeds their content directly into the `edit_config_param.html` page (simple search/replace using https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/tools/parameter-tooltip-generator/generate-param-doc-tooltips.sh)

**Pull request merged**
