### PR TITLE
Update to v2.1.1

### PR DESCRIPTION
**Pull request by jomjol**

### CODE REVIEW

**Comment by jomjol** [comment]
Done by hand

**Comment by renatocascavel** [comment]
My name is Renato. I live in Brazil and working on a master's project since 2018. My project is very similar yours. In your AI-on-the-edge-device version you use CNN to read the numbers from Hydrometer, ok?
In Brazil I have others meters. For each meter I need to create a new CNN, ok?
Can you help me for this?

**Comment by renatocascavel** [comment]
Your model doesn't work for any meter, ok? Your CNN works for your specif meter, ok?

**Comment by renatocascavel** [comment]
I am citing your work in my dissertation.

**Comment by jomjol** [comment]
Hello Renato,
you do not need to make a new CNN for every water meter. The CNN is trained for different kind of digits or analog pointers, respecitvely. You can find details here: https://github.com/jomjol/neural-network-digital-counter-readout
And scroll the image for see the currently trained types. It is rather easy to extend this.

**Comment by renatocascavel** [comment]
Jomjol,

It is a good news!!!
Tks for your answer.  I will test and send the result to you after.

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: segunda-feira, 12 de outubro de 2020 17:41
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,
you do not need to make a new CNN for every water meter. The CNN is trained for different kind of digits or analog pointers, respecitvely. You can find details here: https://github.com/jomjol/neural-network-digital-counter-readout
And scroll the image for see the currently trained types. It is rather easy to extend this.

**Comment by renatocascavel** [comment]
Good morning Jomjol!

I would like to clarify a doubt with you about "neural-network-digital-counter-readout<https://github.com/jomjol/neural-network-digital-counter-readout>". My water meter and gas meter are annex in this mail.

For the neural network to identify the digits do I need to run the learning again with the images of these meters?

Tks for your help.

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: segunda-feira, 12 de outubro de 2020 17:41
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,
you do not need to make a new CNN for every water meter. The CNN is trained for different kind of digits or analog pointers, respecitvely. You can find details here: https://github.com/jomjol/neural-network-digital-counter-readout
And scroll the image for see the currently trained types. It is rather easy to extend this.

**Comment by jomjol** [comment]
Hello Renato,

there is no attachment in this mail.

BR,
   jomjol

------ Originalnachricht ------
Von: "renatocascavel" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device" 
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "State change" 
<state_change@noreply.github.com>
Gesendet: 20.10.2020 14:56:01
Betreff: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)

**Comment by renatocascavel** [comment]
Forgive me. Now the file is annexed.

Tks.

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: terça-feira, 20 de outubro de 2020 14:59
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,

there is no attachment in this mail.

BR,
jomjol

------ Originalnachricht ------
Von: "renatocascavel" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device"
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "State change"
<state_change@noreply.github.com>
Gesendet: 20.10.2020 14:56:01
Betreff: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)

**Comment by jomjol** [comment]
Hello Renato,
I still do not see a file. The communication through a chat in an issue seems not to be the right one. Maybe you find another way to post me the images?
Best regards,
  jomjol

**Comment by renatocascavel** [comment]
I will think something!!

Tks!!

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: terça-feira, 20 de outubro de 2020 18:39
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,
I still do not see a file. The communication through a chat in an issue seems not to be the right one. Maybe you find another way to post me the images?
Best regards,
jomjol

**Comment by renatocascavel** [comment]
Hi Jomjol!!

I would like to share a experience about the solution for focal distance. In my academic work I need to rea only the digital numbers from water meter. To resolve the focal distance problem I am thinking to use a little coin with a litle hole in the middle. This solution looks like when we closing the eyes to read litle letters. I got to minimize the focal distance very well this way.
I'm testing and it looks like it will work.
Best regards,

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: terça-feira, 20 de outubro de 2020 18:39
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,
I still do not see a file. The communication through a chat in an issue seems not to be the right one. Maybe you find another way to post me the images?
Best regards,
jomjol

**Comment by jomjol** [comment]
Hello Renato,

I still do not see any appendix / file or something in your post. Please 
use another way of sending me the information. Using a closed issue or 
update information is not the right way of sending informations. Thanks 
in advance.

If you post your email or send me a personal message, I will reply to 
this and you can send me the image through this. I do not want to post 
my email here directly.

Thanks,
   jomjol

------ Originalnachricht ------
Von: "renatocascavel" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device" 
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "State change" 
<state_change@noreply.github.com>
Gesendet: 21.10.2020 21:31:01
Betreff: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)

**Comment by renatocascavel** [comment]
No problem!!

I sent a mail to you in your gmail.

tks.

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: quarta-feira, 21 de outubro de 2020 18:55
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,

I still do not see any appendix / file or something in your post. Please
use another way of sending me the information. Using a closed issue or
update information is not the right way of sending informations. Thanks
in advance.

If you post your email or send me a personal message, I will reply to
this and you can send me the image through this. I do not want to post
my email here directly.

Thanks,
jomjol

------ Originalnachricht ------
Von: "renatocascavel" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device"
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "State change"
<state_change@noreply.github.com>
Gesendet: 21.10.2020 21:31:01
Betreff: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)

**Comment by renatocascavel** [comment]
Jomjol,

Do you receveid my mail by gmail? If no, is it possible you include me in your Linkedin (Renato Batista Santos)? I would like to talk with you about watermeter solution.

Tks,

Renato

________________________________
De: jomjol <notifications@github.com>
Enviado: quarta-feira, 21 de outubro de 2020 18:55
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


Hello Renato,

I still do not see any appendix / file or something in your post. Please
use another way of sending me the information. Using a closed issue or
update information is not the right way of sending informations. Thanks
in advance.

If you post your email or send me a personal message, I will reply to
this and you can send me the image through this. I do not want to post
my email here directly.

Thanks,
jomjol

------ Originalnachricht ------
Von: "renatocascavel" <notifications@github.com>
An: "jomjol/AI-on-the-edge-device"
<AI-on-the-edge-device@noreply.github.com>
Cc: "jomjol" <mueller.josef@gmail.com>; "State change"
<state_change@noreply.github.com>
Gesendet: 21.10.2020 21:31:01
Betreff: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)

**Comment by jomjol** [comment]
I did not receive an email from you. I don't want to use LinkedIn for this. Why don't you post your email and I will respond to this.

**Comment by renatocascavel** [comment]
Hi Jomjol!!

My mail is renato.cascavel@hotmail.com

________________________________
De: jomjol <notifications@github.com>
Enviado: sábado, 24 de outubro de 2020 07:38
Para: jomjol/AI-on-the-edge-device <AI-on-the-edge-device@noreply.github.com>
Cc: renatocascavel <renato.cascavel@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [jomjol/AI-on-the-edge-device] Update to v2.1.1 (#30)


I did not receive an email from you. I don't want to use LinkedIn for this. Why don't you post your email and I will respond to this.

**Pull request closed without merging**
