### PR TITLE
"WIFI roaming" by channel scan (AP switching at low RSSI)

### PR DESCRIPTION
**Pull request by Slider0007**
Implement a kind of roaming feature #2092 which has less dependencies in terms of capabilities of AP / mesh system and is lightwight to ensure less impact to memory usage of ESP32.

# WIFI AP switching by channel scan (simplified "roaming")
- Implement wifi channel scanning (background scan, scan possible even ESP is connected) to have kind of "roaming" like feature
- Function needs to be activated using RSSIThreshold parameter by setting a value lower than 0 (0 = disable)
- Scan and evaluation gets triggered when actual RSSI < RSSI Threshold (RSSIThreshold, e.g. -75dBm) and flow is finished (Info gets printed with DEBUG level)
image
- Process:
 - Scan all channels for configured SSID
 - Compare if (actual RSSI + 5) < AP RSSIs found by scan (+ 5 to avoid switching by almost equal RSSI)
 - If an AP with better RSSI is found, force wifi disconnect to reconnect to AP with hopefully better RSSI
 - The reconnect to new AP will not get forced by BSSID, to avoid issues when potentially AP with better RSSI reject connection for some reason. Therefore the selection is related to the following config and wifi library.
image
- Switch on all channel scan option --> Wifi scan will performed for all channels before choosing an AP and not use first matching AP (This is also valid even AP switching function is disabled => RSSIThreshold = 0)

# Alternative: WIFI roaming 802.11kv --> deactivated by default
NOTE: Fully implemented, but not fully tested (be aware: additional ca. 6-10kB internal heap is consumed to run this feature)

- basic roaming functionality is disabled by default, compile time (--> This feature needs to be activated in define.h --> #define WLAN_USE_MESH_ROAMING and sdkconfig.default + disabling roaming by scanning feature)
- This is needed to handle any roaming request triggered by AP/mesh (802.11k, 802.11v)
- Optional WIFI roaming feature (needs to be enabled in defines.h --> #define WLAN_USE_MESH_ROAMING_ACTIVATE_CLIENT_TRIGGERED_QUERIES) to enable ESP triggered query to roam using RSSIThreshold parameter can be activated when parameter is set to a value lower than 0 (0 = disable this optional feature)
--> The query is only sent when actual RSSI < RSSI Threshold (RSSIThreshold, e.g. -75dBm)
--> The evaluation is only triggered after flow is finished and RSSI < RSSI Threshold every round (The trigger and the neighbour table gets printed with DEBUG level)
image

--> This does not guarantee that ESP will roam because only a query to AP/mesh is going to be sent. The actual request that ESP needs to roam is still triggered by AP/mesh. If AP/mesh does not see any need to roam, no roam request will sent to ESP and nothing will happen

The info if AP is supporting the roaming features 802.11k and 802.11v will be logged to logfile after wifi connection gets established
image

### CODE REVIEW

**Comment by caco3** [comment]
general question:
With the threshold set to 0, what will happen on the startup? Does it still use the first AP it finds or does it a scan und picks the best one? I would prefer the 2nd option, so also users who do not want to go into expert functions get this improvement. Most might even be unaware or not able to understand what it does.

**Comment by Slider0007** [comment]
> With the threshold set to 0, what will happen on the startup? Does it still use the first AP it finds or does it a scan und picks the best one? I would prefer the 2nd option, so also users who do not want to go into expert functions get this improvement. Most might even be unaware or not able to understand what it does.

The threshold only activates the evaluation to switch APs. If set to 0 no triggered switching will happen.

After any scan always best AP is / should be selected. This a wifi library config setting:
image

**Comment by caco3** [comment]
so the picking of the best AP on startup works also with threshold=0?

**Comment by Slider0007** [comment]
> so the picking of the best AP on startup works also with threshold=0?

yes, as long the wifi library is working correctly

**Pull request merged**
