### PR TITLE
Enhanced flow processing structure: More error handling & parameter reloading without reboot - FOR TESTING

### PR DESCRIPTION
**Pull request by Slider0007**
#2135: Implement an enhanced flow init and flow processing structure to have the possiblity to add more verbose user feedback and additional error handling (reduced execptions) during the main flow init and processing states.

NOTE: Right now, this is only for demonstration and discussion purpose and is not intended to merge directly. This is not based on latest rolling, but somewhere after 15.0.x. 
**Before I continue further I'd like to discuss this with you and would like have some feedback and topics which should be taken care off...**

**The following tasks are prepared for discussion:**
- Main flow process adapted -> new states according the follwing flow chart
- Centralized naming of the flow state names and main flow task states in defines.h
- Flow init with error feedback
  - More verbose feedback what was going wrong
  - Actual flow processing is only getting started if intialization is successful. Possilitly to react to config issues before flow gets started.
- Flow process states with error feedback
  - More verbose feedback what was going wrong
  - Diveded into image processing related states (e.g. Take Image) and publish related states (e.g. Publish to MQTT)
  - Abort processing and go back to Idle state. If issue occured during image processing states, publish states still gets triggered to have the chance to signal the error condition.
  - Signaling errors and avoid execption in special situation (right now only tflite handling and a few others situations covered for demostration purpose. More work needs to be done here after the structure is available)
  - Possiblity to implent an automatic error handling state after the round is completed to avoid reboots and retries in between. Errors states during flow processing gets logged and could be processed after round completed, e.g. after x times no image, reload camera driver or reboot. Not yet implemented, only structure prepared
- Implement a summary message to visualize an issue during flow processing or init. This summary error flag can be provided additionally via MQTT and REST (not yet implemented)
- Updated overview to have more room for information (see example)
- Additional overview images to visualize new states

**Some side work taks which are included in here**
- Add a menu for manual control --> Start Round (exisitng REST API /flow_start)
  - Start a manual flow in every situation and state even automatic flow start is disabled (if running, trigger gets scheduled after round is completed)
- Rename server_tflite -> MainFlowControl and move to jomjol_flowcontroll folder because it's more and less the main file for flow processing
- New strucuture and some additional preconditions give us the possiblity to reload parameter changes without the need of a reboot (only parameter hostname, reboot would potentially still necessary)
  - New parameters can be saved at any time. If process running, they get applied afte round is completed
  - This also works to complete "setup mode". It switches automatically to start screen
  **Mandatory preconditions for parameter reloading without reboot:**
  - All boolean parameters needs to set to TRUE and FALSE. Most of the parameters right now only set if parameter is "true" in config.
  - Destructors for all relevant flow classes got implemented to clean up memory before reload / restart init (this was quite a lot of work)
  --> Parameter reload without reboot needs quite some attention because memory management is essential (reboot cannot solve issues anymore and classes needs to be reloaded to ensure all parameters get read again). A "new" needs always a "delete", a "malloc" needs always a "free", a cosntructor needs always a destructor, ...

**TODOS**
- [ ] Discussion and possible adaptions

PRs:
- [X] Remove ClassWriteList --> #2264
- [X] Rename server_tflite.cpp --> #2265
- [ ] Updated overview page
- [ ] Implement new flow structure + new states
- [ ] Add error handling for CNN processing, TFlite files
- [ ] Optimize camera class
- [ ] Add flow start to WebUI
   For parameter reloading:
- [ ] Add destructors for every class
- [ ] ReadParameter: boolean parameters needs to be set to TRUE and FALSE
- [ ] Save and apply to ROI pages, setup mode, configuration page
- [ ] Reload of RSSIThreshold
- [ ] Reload of Timezone change
- [ ] Verify hostname reloading

Example 1: Process without errors:
image

Example 2: Initialization error - "TFLite file not exisitng"
image
image

Example 3: Automatic flow start disabled
image

Overview of structure (dotted -> new):
**(Note: The correct visualization seems sometimes not working with GitHub app. Please use WebView on PC or cell)**

```mermaid
flowchart TD

A[Start flow task] --> A1{Flow task created}
A1 -.->|NO| A2[Flow task creation failed]
A1 -->|YES| A3{Rebooted <br> due to execption?}
A3 -->|YES| B[Initialization delayed] --> B1{Delay time of <br> 5min elapsed?}
B1 -->|YES| C
A3 -->|NO| C[Initialization] -->C1{Init OK?}
C1 -.->|NO| D[Initialization failed]
C1 -->|OK| C2{Setup mode?} 
C2 -->|YES| E[Setup mode]
C2 -->|NO| C3{Flow autostart <br> enabled?}
C3 -.->|NO| F[Idle - no autostart]
C3 -->|YES| G[Take Image] --> G1{Flow OK?}
G1 -->|YES| H[Image alignment] --> H1{Flow OK?}
H1 -->|YES| I[Digitalization of ROIs <br> digital] --> I1{Flow OK?}
I1 -->|YES| J[Digitalization of ROIs <br> analog] --> J1{Flow OK?}
J1 -->|YES| K[Post-Processing] --> K1{Flow OK?}
K1 -->|YES| L[Publish to MQTT] --> L1{Flow OK?}
L1 -->|YES| M[Publish to InfluxDB] --> M1{Flow OK?}
M1 -->|YES| N[Publish to InfluxDBv2] --> N1{Flow OK?}
N1 -.->|YES| Q[Additional tasks] -.-> Q1{Error during <br> image/publish process}
Q1 -.->|YES| Q2[Automatic error <br> handling]
Q1 -.->|NO| O
Q2 -.-> O[Idle - Waiting for autostart] --> O1{Autotimer elasped?} --> G

G1 -.->|NO| P(Set summary error flag)
H1 -.->|NO| P
I1 -.->|NO| P
J1 -.->|NO| P
K1 -.->|NO| P
L1 -.->|NO| P
M1 -.->|NO| P
N1 -.->|NO| P
```

### CODE REVIEW

**Comment by jomjol** [comment]
Wow - great of work and documentation! 

I like the idea and improvements! I have checked some ideas in the main flow and like especially the additional error handling. From my point of view we can go into that direction. The main isssue for me is, how to make a smooth transition to this refactored flow? Now we have a well tested and in small steps improved and debugged version. Ususally with implementing such a hugh change, there are quite some minor bugs to be found and removed.
How can we handle this effectively?

**Comment by caco3** [comment]
On my system I get crashes immediately after startup:
```
I (6122) MAIN: =================================================
I (6162) MAIN: ==================== Start ======================
I (6202) MAIN: =================================================
I (6242) SDCARD: Basic R/W check started...
I (6322) SDCARD: Basic R/W check successful

abort() was called at PC 0x401f61ae on core 0


Backtrace:0x40083d11:0x3ffc2b200x4008e929:0x3ffc2b40 0x40095109:0x3ffc2b60 0x401f61ae:0x3ffc2bd0 0x40190bff:0x3ffc2bf0 0x4017d04e:0x3ffc2c10 0x4017eaa3:0x3ffc2c30 0x4017ebf3:0x3ffc2c50 0x400df70b:0x3ffc2c80 0x400d4f52:0x3ffc2d80 0x4021884e:0x3ffc2ee0 
```

**Comment by Slider0007** [comment]
> On my system I get crashes immediately after startup:

@caco3: I haven't changed anything in boot logic.
So I traced your log. This pointed me to timesetup function. Your "time zone" parameter is potentially empty (from some tests before?). Can you please verify.
I did a test with empty time zone and also have the bootloop you posted. See issue report #2198

So this issue seems not related to the changes in this PR.

**Comment by caco3** [comment]
> So this issue seems not related to the changes in this PR. So maybe you can give it another try :-) Thanks!

You are absolutely right!

I even fixed it myself in https://github.com/jomjol/AI-on-the-edge-device/commit/d9cb0e1d66af170c1175dd7fdc2531fb2ee71260 :facepalm:

**Comment by haverland** [comment]
Works fine since 24h on my watermeter. I imagine if we can show more than one status in the box:
image

So it could show a last error and the newer idle message.

**Comment by haverland** [comment]
> @jomjol, @caco3, @haverland: Any further comments / remarks to this approach?
> 
> I'd like to start splitting up the large topic in smaller PRs based on latest rolling in the next time.
> 
> Implementation approach:
> 
> * Some preparation PRs (renaming, ...)
> * One PR with new flow basic structure -> needs to be discussed when it's a good time slot to implement
> * Based on new flow structure multiple PRs to add more error handling to specific classes / function groups

Runs fine since a week now without any issue on my watermeter.

**Comment by Slider0007** [comment]
Closing for now. Possible to reopen any time in the future...

**Pull request closed without merging**
