### PR TITLE
Support crop image on sensor, grayscale, and auto exposure level

### PR DESCRIPTION
**Pull request by jasaw**
Features:
1. Camera takes 1600x1200 resolution cropped to 640x480, or 800x600 cropped to 640x480 (or 320x240 depends on config). Only tested extensively on OV2640 camera.
2. Grayscale mode works with brightness/contrast/saturation control.
3. Adjustable auto exposure level, which is very important for certain lighting conditions.
4. Option to choose "Auto Exposure Control 2" algorithm for auto exposure. This might fix some under-exposed or over-exposed issues.
5. Negative photo effect might work better with existing digit models.

All these features are done by the camera itself, so no impact on memory usage or performance of the ESP32.

Discussion here: https://github.com/jomjol/AI-on-the-edge-device/discussions/2733

This is my test setup where the camera is taking 1600x1200 and cropping 640x480 out of it.
gasmeter_zoomed_negative_1

### CODE REVIEW

**Comment by caco3** [comment]
Thank you for your contribution!

Can you please do the following:
- [ ] Rebase to latest rolling
- [ ] Add the defaults of each parameter to the `sd-card/config/config.ini`
- [ ] For each new parameter, add a parameter description in `param-docs/parameter-pages`. Check the https://github.com/jomjol/AI-on-the-edge-device/tree/rolling/param-docs#readme. I can help you if needed. Those pages will be used for the tooltips on the config page as well as for the online documentation.
- [ ] I think it would be good to also add the parameters to the config page. I can help you if needed.

**Comment by jasaw** [comment]
@caco3 I've done these:

- [ ] rebase to latest rolling
- [ ] add defaults to `sd-card/config/config.ini`
- [ ] add parameter description to documentaion in `param-docs/parameter-pages`.
- [ ] add parameters to config page. I haven't quite figured out what those suffix in `<tr id>` mean, like `_ex10`, or `_ex8`, or `ex3`.

If you can help me with those parameters in the config html page, that would be greatly appreciated.

**Comment by caco3** [comment]
Dear @jasaw 

Thank you for your contribution, especially the detailed parameter documentation! I will add the parameters to the config page, but it will take me a moment as live is quite busy atm.

**Comment by caco3** [comment]
I merged it to  jomjol:feature/crop_image  so I can edit the files of it

**Pull request merged**
