### PR TITLE
add whitespaces in JSON in MQTT

### PR DESCRIPTION
**Pull request by caco3**
See https://github.com/jomjol/AI-on-the-edge-device/issues/1468

### CODE REVIEW

**Comment by gorddel** [comment]
@caco3 
The whitespace added to JSON string published to MQTT by this change are extremely problematic for me and have caused me to revert to Version 12.0.1. When Mosquitto clients subscribe to that topic, they receive the JSON string broken into newlines at each space. This makes it impossible to handle that JSON string in other scripts. Please revert this change to produce industry standard JSON MQTT strings.
(Sorry, I'm a github novice and I'm not sure if replying to a closed issue is the proper way to address this, or if I should open a new issue).

**Comment by caco3** [comment]
Hi @gorddel 

Yes, it is the right place to refer to  a specific change.

Can you please refer me to that mentioned industry standard?
To my knowledge, whitespaces are allowed. See also https://stackoverflow.com/questions/4150621/are-whitespace-characters-insignificant-in-json where it even refers to an RFC! Also, testing it with shows it is valid: https://jsonformatter.curiousconcept.com/?data={%20%20%20%22key%22:%20%20%20%20%20%20%20%20%22value%22%20%20%20%20%20}&process=true# (on the right side you can even select the RFC to check for, they all show it as valid).

I also use Mosquitto and do not see any issue with it.
So, no, I do not see why we need to change it on our side, please have a look on your script side! Maybe the string is just wrapped around because it is too long?

**Comment by gorddel** [comment]
Hi @caco3 

Thanks very much for your quick reply. Perhaps my phrase of "industry standard" was overstated - you are correct that spaces are allowed in the JSON strings. However, of the many MQTT devices I that use, Tasmota, Zigbee2MQTT, etc, most of them format JSON strings for MQTT without additional spaces. 

I'll dig deeper into things on my side and see how I can handle this change on my end going forward. 

Thanks again for your input and consideration. Jomjol, you, and the others that have created, enhanced, and support this amazing project deserve high praise indeed! I'm awestruck by the amount of functionality that you have packed into an ESP32!

**Comment by caco3** [comment]
Thanks for your undertsanding!

They most likely remove the whitespace to save a bit of memory.
I on purpose added the whitespace so a client is able to wrap the string when it is too wide.
Example:
grafik

Without the whitespaces, you only would see the first part of the whole message-

**Pull request closed without merging**
