### PR TITLE
Update Changelog.md

### PR DESCRIPTION
**Pull request by caco3**
- [ ] Cleanup the README.md (move parts of it to the docs)
- [x] Check changelog for completeness
- [x] Add latest changes to changelog
- [x] Decide if we do a release 14.0.0 or a Pre-Release (resp. Release Candidate 14.0.0-RC1)
- [x] In manual setup zip, move all folders in folder `sd-card` a level higher

I used the `tig` command to get a summary of all changes since the last release.
IMO this is cleaner than looking on https://github.com/jomjol/AI-on-the-edge-device/compare/v13.0.8...HEAD

```
2023-01-21 21:54 +0100 CaCO3              o [rolling] {origin/rolling} {origin/HEAD} Remove newline in version (#1891)
2023-01-21 21:33 +0100 CaCO3              o Update Changelog.md
2023-01-21 21:32 +0100 CaCO3              o Update Changelog.md for  release (#1892)
2023-01-21 09:24 +0100 CaCO3              o Update config.ini (#1880)
2023-01-21 09:24 +0100 Slider0007         o Show WIFI signal text labels / Log RSSI value to logfile (#1877)
2023-01-21 00:10 +0100 CaCO3              o fixed typo (#1881)
2023-01-19 18:22 +0100 Nicolas Liaudat    o Revert "add AlignmentAlgo=off option (#1867)" (#1876)
2023-01-19 18:21 +0100 Slider0007         o Replace outdated wiki links, wording (#1871)
2023-01-18 23:01 +0100 Nicolas Liaudat    o add AlignmentAlgo=off option (#1867)
2023-01-18 13:59 -0800 AngryApostrophe    o Update ota_page.html (#1866)
2023-01-18 22:58 +0100 Nicolas Liaudat    o disable HIMEM (external > 4mb ram) not used (#1864)
2023-01-18 22:57 +0100 Nicolas Liaudat    o Heap tracing (#1861)
2023-01-18 22:55 +0100 CaCO3              o Improve data logging on errors (#1839)
2023-01-17 21:12 +0100 CaCO3              o Update build.yaml
2023-01-16 23:07 +0100 Slider0007         o Avoid multiple Access-Control-Allow-Origin * (#1859)
2023-01-16 00:12 +0100 CaCO3              o fix define
2023-01-15 22:42 +0100 Nicolas Liaudat    o add HIMEM debugging tools (check free size, and memory test) (#1852)
2023-01-15 22:41 +0100 Nicolas Liaudat    o enhance development environment (#1841)
2023-01-15 15:22 +0100 CaCO3              o update wiki references
2023-01-15 15:06 +0100 CaCO3              o [release-notification] {origin/release-notification} Show ways to get notified about new releases
2023-01-14 23:11 +0100 CaCO3              o Fix uninitialized filename (#1838)
2023-01-14 16:47 +0100 CaCO3              o Update label-commenter-config.yml
2023-01-14 16:02 +0100 CaCO3              o improve caching (#1836)
2023-01-14 13:43 +0100 jomjol             o Initial Implementation (#1835)
2023-01-14 13:41 +0100 Nicolas Liaudat    o Fix pointer call in ClassControllCamera.cpp:310 (#1833)
2023-01-14 13:28 +0100 jomjol             o Initial Implementation (#1834)
2023-01-14 11:24 +0100 jomjol             o Update tflite
2023-01-14 11:21 +0100 Nicolas Liaudat    o update build actions/cache@v3.2.3 (#1831)
2023-01-14 10:15 +0100 Nicolas Liaudat    o git ignore + sdkconfig.esp32cam-dev (#1830)
2023-01-14 10:14 +0100 Nicolas Liaudat    o Esp32 sys info (#1829)
2023-01-14 00:44 +0100 CaCO3              o Update README.md
2023-01-14 00:28 +0100 CaCO3              o Delete clean-branch-cache-after-pull-request-got-closed.yml
2023-01-14 00:26 +0100 Nicolas Liaudat    o Clean sdkconfig (not default) (#1828)
2023-01-14 00:12 +0100 CaCO3              o Create clean-branch-cache-after-pull-request-got-closed.yml
2023-01-13 22:05 +0100 Slider0007         o Store preprocessed image with ROI to RAM (#1809)
2023-01-13 21:00 +0100 jomjol             o Update links
2023-01-13 20:40 +0100 jomjol             o Improve html roi disablement (#1825)
2023-01-13 20:09 +0100 Nicolas Liaudat    o [fix-pipeline-cache$] plaformio [env:esp32cam-dev] : Add task analysis & test for 8m spiram  real support (#1818)
2023-01-12 19:27 +0100 Slider0007         o DataGraph: datafiles sorted -> newest on top (#1817)
2023-01-12 19:27 +0100 Slider0007         o Refactor getEspHeapInfo routine (#1816)
2023-01-12 19:26 +0100 Slider0007         o REST handler sysinfo + MQTT topic: Free heap memory not reporting (#1815)
2023-01-11 20:50 +0100 CaCO3              o Delete demo-images directory
2023-01-11 20:24 +0100 Slider0007         o Update graph.html (#1802)
2023-01-11 20:23 +0100 Slider0007         o Add error handling for memory intensive tasks (#1798)
2023-01-11 20:21 +0100 jomjol             o STBI_ONLY_JPEG (#1789)
2023-01-10 19:37 +0100 Slider0007         o Rest handler: Use none chunked transfer (#1797)
2023-01-10 19:36 +0100 Slider0007         o GPIO handler: Deinit before delete (#1795)
2023-01-09 21:49 +0100 CaCO3              o fix overview.html
2023-01-08 19:18 +0100 CaCO3              o Ignore cache on GIT hash change (new commit or release) (#1787)
2023-01-08 12:36 +0100 CaCO3              o Improve file server (#1785)
2023-01-08 12:35 +0100 Nicolas Liaudat    o Add option to disable brownout detector (#1784)
2023-01-08 12:32 +0100 jomjol             o Update platfromio.ini
2023-01-07 20:24 +0100 Slider0007         o Rolling-bot: Only show jomjol repo rollings (#1783)
2023-01-07 20:21 +0100 CaCO3              o new OTA page with progressbar (#1756)
2023-01-04 20:31 +0100 CaCO3              o cache static files (#1755)
2023-01-03 08:24 +0100 jomjol             o Optimized CImageBasis
2023-01-03 08:10 +0100 Slider0007         o Modify stack sizes + max open files (SD) , add REST handler for heap/(stack) infos (#1751)
2023-01-03 08:06 +0100 Nicolas Liaudat    o compiler optimization (#1749)
2023-01-03 08:05 +0100 CaCO3              o Replace alert boxes with overlay info boxes  (#1742)
2023-01-02 14:31 +0100 CaCO3              o consolidate test-ip definition, added missing Access-Control-Allow-Origin (#1741)
2023-01-02 00:55 +0100 CaCO3              o Revert "consolidate test-ip definition, added missing Access-Control-Allow-Origin,"
2023-01-02 00:53 +0100 CaCO3              o consolidate test-ip definition, added missing Access-Control-Allow-Origin,
2023-01-01 19:23 +0100 Frank Haverland    o #1649 unnecessary np check (#1736)
2022-12-31 20:16 +0100 CaCO3              o Update build.yaml (#1737)
2022-12-31 11:15 +0100 jomjol             o Update SoftAP
2022-12-30 22:48 +0100 jomjol             o Moved softAP to the very first checks
2022-12-30 21:58 +0100 Slider0007         o Fix regression of reboot handler / reboot waiting script (#1725)
2022-12-30 21:57 +0100 CaCO3              o Add demo mode (#1720)
2022-12-30 09:15 +0100 CaCO3              o improve explanations,added example (#1729)
2022-12-30 00:11 +0100 CaCO3              o Update defines.h (#1726)
2022-12-29 22:24 +0100 jomjol             o Create demo folder at startup (if not present)
2022-12-29 16:39 +0100 CaCO3              o fix static IP in UP, improve explanation for HA (#1719)
2022-12-29 16:23 +0100 CaCO3              o Improve log message when web UI is incomplete (#1716)
2022-12-29 10:16 +0100 Slider0007         o Force a reboot even reboot task cannot be created due to lack of heap (#1713)
2022-12-28 21:31 +0100 Slider0007         o Avoid loading of status infos twice (#1711)
2022-12-28 15:21 +0100 jomjol             o Update server_ota.cpp
2022-12-28 15:07 +0100 jomjol             o Update Reboot Algo
2022-12-28 14:32 +0100 jomjol             o Move Logfile Switch to define.h
2022-12-28 14:28 +0100 jomjol             o add a define to configure the logfile handling (#1709)
2022-12-28 13:10 +0100 jomjol             o Update defines
2022-12-28 12:43 +0100 jomjol             o Enable SoftAP
2022-12-28 12:34 +0100 Nicolas Liaudat    o Safe optimizations (#1706)
2022-12-27 20:30 +0100 Slider0007         o fetch index.html after reboot -> less 404 (#1705)
2022-12-27 20:29 +0100 Slider0007         o Deinit components before reboot (#1704)
2022-12-27 19:04 +0100 Nicolas Liaudat    o macro definition #ifdef ENABLE_SOFTAP (#1698)
2022-12-27 19:01 +0100 Nicolas Liaudat    o delete img_convert.h as included in code\components\tflite-micro-esp-… (#1695)
2022-12-27 18:54 +0100 CaCO3              o disable remove-labels because they no longer work
2022-12-27 18:21 +0100 CaCO3              o Update label-commenter-config.yml
2022-12-27 18:11 +0100 CaCO3              o Add Bot Replies (#1701)
2022-12-27 10:20 +0100 jomjol             o Improve initial setup proc (#1692)
2022-12-27 07:18 +0100 CaCO3              o Extend Github Actions (#1680)
2022-12-27 00:04 +0100 CaCO3              o make more robust, add log (#1690)
2022-12-26 21:14 +0100 CaCO3              o prepare docs for deployment through actions (#1688)
2022-12-24 11:58 +0100 CaCO3              o fix special case where number is named "default" (keep all topics in top level instead of in a sub-group) (#1664)
2022-12-23 22:45 +0100 CaCO3              o Improve NTP handling (#1676)
2022-12-22 21:43 +0100 Frank Haverland    o Remove unnecessary null pointer checks #1649 (#1673)
2022-12-22 18:51 +0100 jomjol             o Update HTML & Firmware (#1671)
2022-12-22 08:10 +0100 Slider0007         o Init GPIO handler before MQTT init (#1663)
2022-12-21 21:45 +0100 CaCO3              o Update sdkconfig.defaults (#1661)
2022-12-21 21:26 +0100 CaCO3              o show release in log instead of branch (#1660)
2022-12-21 17:45 +0100 CaCO3              o Optimize logfile write (#1652)
2022-12-21 17:45 +0100 Slider0007         o Trigger a flow start by REST API or MQTT (#1648)
2022-12-20 06:47 +0100 Nicolas Liaudat    o Update defines.h (#1640)
2022-12-20 06:46 +0100 Nicolas Liaudat    o #ifndef in *.h + #pragma once (#1639)
2022-12-19 23:17 +0100 CaCO3              o Add files via upload
2022-12-19 23:14 +0100 CaCO3              o Update manifest.json
2022-12-19 22:05 +0100 Nicolas Liaudat    o Code translation (#1626)
2022-12-19 21:59 +0100 jomjol             o Update WebInstaller
2022-12-19 21:59 +0100 jomjol             o Update WebInstaller
2022-12-19 21:54 +0100 jomjol             o Update defines.h
2022-12-19 21:43 +0100 Nicolas Liaudat    o Centralizing the defines (#1624)

```

### CODE REVIEW

**Comment by caco3** [comment]
@jomjol @haverland @Slider0007 @nliaudat @AngryApostrophe Please go through the list and check if there is something important missing

**Comment by jomjol** [comment]
@caco3 : MANY thanks for starting the release procedure!
* I have updated the readme at minor points - from my point of view okay

I suggest a pre release:
1. Merge everything in master (otherwise the WebInstaller will not work)
2. Make a prereleaes (v14.0.0-RC1) to indicate that we THINK we are done, but still need some testing 

I have moved the update descripton out of the changelog.md to the documentation (https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#update)

**Comment by Slider0007** [comment]
Changelog seems good from my side, thanks for preparation. Only maybe the last commit with replacement of images should be mentioned because it's so obvious on the UI.

What we need  to taking care off before the release is the renaming of the update zip files in documentation. Files are not called update_VERSION.zip anymore.

Also what came in mind: Is it possible to have in sd-card.zip no more subfolder sd-card but just the folders and files which needs to go to sd-card root? This would avoid that users just copy the sd-card folder to SD card root.

**Comment by caco3** [comment]
> I have updated the readme at minor points

I was thinking of simplifying the readme with:
 - removing the whole **Setup** section and instead link to the documentation.
- remove the **Tools** section 
- move the casing to the documentation

> I have moved the update description out of the changelog.md to the documentation (https://jomjol.github.io/AI-on-the-edge-device-docs/Installation/#update)

That is great!

> the last commit with replacement of images should be mentioned because it's so obvious on the UI.

Yes, right, i missed that.

> What we need to taking care off before the release is the renaming of the update zip files in documentation. Files are not called update_VERSION.zip anymore.

That is right, but one of the reason of having the documentation in a separate repo is to make updating easier as we do not need to clutter the main repo.

>  Is it possible to have in sd-card.zip no more subfolder sd-card but just the folders and files which needs to go to sd-card root?

Yes, that seems to be a bug. I will fix it.

**Comment by Slider0007** [comment]
>> What we need to taking care off before the release is the renaming of the update zip files in documentation. Files are not called update_VERSION.zip anymore.

>That is right, but one of the reason of having the documentation in a separate repo is to make updating easier as we do not need to clutter the main repo.

Sorry to be unclear in my statement. The docu in general is totally fine. I was just talking about these chapters in the docu which needs to be adapated to new file naming.

image
image


I updated them already. Hope this is OK for you guys...



> > Is it possible to have in sd-card.zip no more subfolder sd-card but just the folders and files which needs to go to sd-card root?
> 
> Yes, that seems to be a bug. I will fix it.

Thanks!

**Comment by caco3** [comment]
> Hope this is OK for you guys... 

Yes, I would say please go ahead unless you are unsure and want a review.

**Pull request merged**
