### PR TITLE
make input number box wider to display at least 3 digits.

### PR DESCRIPTION
**Pull request by kalwados**
Both edit_analog.html and edit_digits.html now uses the same styles.

### CODE REVIEW

**Comment by caco3** [comment]
@kalwados can you please fix the conflicts?

**Comment by kalwados** [comment]
> @kalwados can you please fix the conflicts?

First of all: Sorry for my bad code. Something went wrong with my pull request. I'm new to Git/Github. Is there a way to undo/revert/delete my pull request?

**Comment by caco3** [comment]
Your code and Pull Request was completely fine and I think its a good idea!
But sadly we kept it open for too long and now there is a conflict to be solved. That is not your fault!

**Comment by kalwados** [comment]
I've created a new pull request.

**Pull request closed without merging**
