### PR TITLE
Boot phase: Add more error handling + provide verbose output in error cases

### PR DESCRIPTION
**Pull request by Slider0007**
General goal: Provide more verbose output to the user in error cases or misconfiguration in boot phase (this PR only covers till start of flow task) and try to prevent against execptions is such situations.

- Add more error handling for read wlan.ini, wlan init --> #1884
- Log different WLAN disconnect reasons (error codes to be described in documentation; 
source: https://github.com/espressif/esp-idf/blob/d825753387c1a64463779bbd2369e177e5d59a79/components/esp_wifi/include/esp_wifi_types.h#L69
- Return RSSI value -127, if not connected (for logfile logging)
- Use red board LED to visualize different error states (error codes to be described in documentation)
  - General approach:
    - Number of blink codes for error source
    - Defined delay (500ms)
    - Number of blinks for several errors codes of specific source
    - Delay to signal next round (only if infinite blinking)
    - LED is still signaling flashlight on duration (lower priority, only if no error is pending)
  - NOTE: Previous blink task for SD error and WLAN connect removed

| **source**    | source blink code | status                                | status blink code | infinite loop |
| ------------- | ----------------- |---------------------------------------| ---------------- | --- |
| FLASHLIGHT    | N/A               | LED on when flashlight is on (lower prio than other sources) | solid, no blinking
| WLAN_CONN     | 1                 | Disconnected (No Access Point)        | 1                |
| WLAN_CONN     | 1                 | Disconnected (Authentication failure) | 2                |
| WLAN_CONN     | 1                 | Disconnected (Timeout)                | 3                |
| WLAN_CONN     | 1                 | Disconnected (Error code, misc error) | 4                |  
| WLAN_INIT     | 2                 | WLAN.ini empty or not readable        | 1                | X
| WLAN_INIT     | 2                 | SSID or password empty                | 2                | X
| WLAN_INIT     | 2                 | WIFI init error (details console)     | 3                | X
| SDCARD_INIT   | 3                 | SD filesystem mount failed            | 1                | X
| SDCARD_INIT   | 3                 | SD not found (0x107)                  | 2                | X
| SDCARD_INIT   | 3                 | SD init failed (details console)      | 3                | X
| SDCARD_CHECK  | 4                 | Failed to create directories          | 1                |
| CAM_INIT      | 5                 | Camera init failed (details console)  | 1                | X
| CAM_INIT      | 5                 | Camera framebuffer check failed       | 2                | 
| PSRAM_INIT    | 6                 | PSRAM init failed: Not found/defective| 1                | X
| PSRAM_INIT    | 6                 | External PSRAM < 4MB                  | 2                | X
| PSRAM_INIT    | 6                 | Total heap < 4MB                      | 3                | X
| TIME_CHECK    | 7                 | Missing time sync                     | 1                |
| OTA_OR_AP     | 8                 | OTA process ongoing                   | 1                | X
| OTA_OR_AP     | 8                 | Soft AP started                       | 2                | X

- WLAN.INI:
  - Add more infos to respective parameters
  - Align output to file (including description rows) when generating by softAP or functions "change of hostname or change of RSSIThreshold"
  - Align different names for RSSIThreshold (RSSIThreashold, rssi) when file is going to be updated
  - Use a global struct to store WLAN configuration
  - Log WLAN.INI parameters to logfile (for diagnostic purpose)
 
- RSSIThreshold: check for correct input (range -100 - 0)

- main.cpp
  - Restructure and combine some already available infos, e.g. reset reason including description of delayed start in one block
  - Ensure DEBUG level is kept during flow in case of execption reset
  - Print device, RAM, SD and camera infos to logfile (for diagnostic purpose)
  - Hightlight start of log in console logging (start main_app) and logfile logging (print only one block before first logfile entry)

- Renaming of some log file entries
  - softAP, OTA, main
 
- Create additional default folders on sd card at startup (firmware, img_tmp) (if not available) to prevent against exceptions

I did quite some testing. Due to the larger changes, it needs to be tested further.
Please see this PR as a proposal. Optimizations or comments are warmly welcome. 

Questions:
- [x] Camera framebuffer test was only performed when camera init failed once. Is there a reason not performing this in every case?
--> I prepared testing at any case.
- [x] WLAN connected not signaling via LED anymore because LED is more or less an error indication LED. Any concerns?
- [x] Should wifi disconnect / mqtt disconnect messages set to WARN level? I prepared with INFO level
--> Switched to WARN + additional ERROR after multiple attempts

Further steps:
- Based on this PR, provide an additional PR with some basic SD card checks and related error handling in early boot phase to have early indication of potentially SD card issues --> #1886
- Based on this PR, provide an additional PR to fully implement wlan roaming function including related error handling.
@jomjol: Working on this PR I figured out, that basic roaming functions are implemented, but sdkconfig and wifi config flags are not yet set, therefore roaming functioanlity is not acitvated right now. To activate roaming, enough heap needs to be provided first to prevent potential device crash (roaming needs at least 8-10kB additional heap which is not guaranteed in actual configuration). I'll provide an proposal, if it's ok for you.

### CODE REVIEW

**Comment by nliaudat** [comment]
Great !
I propose to add blink codes for : 

- setupTime() = false : wifi ok, but no internet
- OTA update in progress
- SoftAP started

All the device info have buildin functions in components\jomjol_helper\esp_sys.cpp
Regards

**Comment by nliaudat** [comment]
#ifdef preprocessor directives should not be indented :
```
#ifdef __SD_USE_ONE_LINE_MODE__
    slot_config.width = 1;
#endif
```
_Bad code readability, confusion with traditional if statement :_ 
```
    #ifdef __SD_USE_ONE_LINE_MODE__
        slot_config.width = 1;
    #endif
```

**Comment by Slider0007** [comment]
@nliaudat: Thanks for your proposal:

> * setupTime() = false : wifi ok, but no internet

--> I prepared this, but only checking if time is synced after each round.

> * OTA update in progress
> * SoftAP started

--> I prepared this

**Comment by Slider0007** [comment]
@jomjol, @caco3: This one is ready for testing. Please have a look to the open questions.

**Comment by caco3** [comment]
I just read the description, its quite impressive!

> Camera framebuffer test was only performed when camera init failed once. Is there a reason not performing this in every case? I prepared testing at any case.

what do you mean with this?
the test itself will not fix the problem, right?
but we could repeat the init periodically.

> WLAN connected not signaling via LED anymore because LED is more or less an error indication LED. Any concerns?

You mean the red LED? Thats ok for me, we just need to document it properly in the changelog.

> Should wifi disconnect / mqtt disconnect messages set to WARN level? I prepared with INFO level

you mean if the log message should we a warning instead of info?
For a disconnect I would go for warning as it something disturbing the expected operation.
and if a re-connect fails, we even could show an error log message

**Comment by Slider0007** [comment]
@caco3: Thanks for your feedback.

> > Camera framebuffer test was only performed when camera init failed once. Is there a reason not performing this in every case? I prepared testing at any case.
> 
> what do you mean with this? the test itself will not fix the problem, right? but we could repeat the init periodically.

During analysis of boot procedure I realized that the existing test framebuffer function was only called when the init of camera failed once before. Therefore I wasn't sure if this was designed by purpose. I rearranged it now that way, that this already existing framebuffer test function is called every start independed of previous camera condition. In my environment it changes nothing, so I think it should not an issue. And yes, this function does not fixing the problem, it just calls the framebuffer once if available test is successful if not it will fail like before.

> > WLAN connected not signaling via LED anymore because LED is more or less an error indication LED. Any concerns?
> 
> You mean the red LED? Thats ok for me, we just need to document it properly in the changelog.

Yes, the red LED. I would just mention it here, maybe there was a special reason to have this. For sure it'll be described the docu and/or changelog

> > Should wifi disconnect / mqtt disconnect messages set to WARN level? I prepared with INFO level
> 
> you mean if the log message should we a warning instead of info? For a disconnect I would go for warning as it something disturbing the expected operation. and if a re-connect fails, we even could show an error log message

Thanks. I'm going to switch the disconnect messages to WARN level and added an additional ERROR message whenever multiple reconnect attempts (>10) failed to ensure that it will be visible even with logging level ERROR.

**Comment by jomjol** [comment]
> * Based on this PR, provide an additional PR to fully implement wlan roaming function including related error handling.
>       @jomjol: Working on this PR I figured out, that basic roaming functions are implemented, but sdkconfig and wifi config flags are not yet set, therefore roaming functioanlity is not acitvated right now. To activate roaming, enough heap needs to be provided first to prevent potential device crash (roaming needs at least 8-10kB additional heap which is not guaranteed in actual configuration). I'll provide an proposal, if it's ok for you.

I was not aware of this, so if you have an idea, how to guarantee the heap, we should enable it.

**Comment by nliaudat** [comment]
I've tried to update following ways : 

1. 15.0.0 => [AI-on-the-edge-device__update__2020_merge_(b052f3f)](https://github.com/jomjol/AI-on-the-edge-device/suites/11201037179/artifacts/572763098) = firmware still stay to 15.0.0
2. 14.0.3 => [AI-on-the-edge-device__update__2020_merge_(b052f3f)](https://github.com/jomjol/AI-on-the-edge-device/suites/11201037179/artifacts/572763098) = firmware still stay to 14.0.3
3. 14.0.3 => firmware.bin only from your commit = ok


I got 
```
I (96721) OTA FILE: Filename to extract: /sdcard/html/param_tooltips/flipImageSize.png, Zwischenfilename: /sdcard/html/param_tooltips/flipImageSize.png_0xge
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x401fd67d  PS      : 0x00060930  A0      : 0x801fd700  A1      : 0x3ffd5eb0  
A2      : 0x3ffd66d8  A3      : 0x00029cad  A4      : 0x00000001  A5      : 0x00029cad
A6      : 0x00000000  A7      : 0x0000000c  A8      : 0x801fd67d  A9      : 0x3ffd5e90  
A10     : 0x00000000  A11     : 0x3ffd5ec4  A12     : 0x00000601  A13     : 0x000001b6
A14     : 0x3ffcf568  A15     : 0x3ffd66d8  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000064  LBEG    : 0x4008a416  LEND    : 0x4008a421  LCOUNT  : 0x00000000
Backtrace:0x401fd67a:0x3ffd5eb00x401fd6fd:0x3ffd5ef0 0x400ec25c:0x3ffd5f10 0x400ee302:0x3ffd64d0 
ELF file SHA256: 36bfe5f23904cffe
Rebooting...
```

and 
```

I (28631) OTA FILE: uri: /log
I (28641) OTA FILE: File contains 46368 bytes
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core  0 register dump:
PC      : 0x4020707b  PS      : 0x00060c30  A0      : 0x800f41b1  A1      : 0x3fff1470  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3f414701  A5      : 0x00000000
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800f3108  A9      : 0x3fff1440  
A10     : 0x3fff1608  A11     : 0x3f414701  A12     : 0x3f414701  A13     : 0x0000ff00
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000013  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000044  LBEG    : 0x4008a274  LEND    : 0x4008a290  LCOUNT  : 0xffffffff
Backtrace:0x40207078:0x3fff14700x400f41ae:0x3fff1490 0x400ef3f0:0x3fff1690 0x40109351:0x3fff1750 0x401097a6:0x3fff17a0 
ELF file SHA256: 36bfe5f23904cffe
Rebooting...
```

I mean it's related to my sdcard which is end of life.

**Comment by Slider0007** [comment]
> I got
> 
> ```
> I (96721) OTA FILE: Filename to extract: /sdcard/html/param_tooltips/flipImageSize.png, Zwischenfilename: /sdcard/html/param_tooltips/flipImageSize.png_0xge
> Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
> 
> Core  0 register dump:
> PC      : 0x401fd67d  PS      : 0x00060930  A0      : 0x801fd700  A1      : 0x3ffd5eb0  
> A2      : 0x3ffd66d8  A3      : 0x00029cad  A4      : 0x00000001  A5      : 0x00029cad
> A6      : 0x00000000  A7      : 0x0000000c  A8      : 0x801fd67d  A9      : 0x3ffd5e90  
> A10     : 0x00000000  A11     : 0x3ffd5ec4  A12     : 0x00000601  A13     : 0x000001b6
> A14     : 0x3ffcf568  A15     : 0x3ffd66d8  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
> EXCVADDR: 0x00000064  LBEG    : 0x4008a416  LEND    : 0x4008a421  LCOUNT  : 0x00000000
> Backtrace:0x401fd67a:0x3ffd5eb00x401fd6fd:0x3ffd5ef0 0x400ec25c:0x3ffd5f10 0x400ee302:0x3ffd64d0 
> ELF file SHA256: 36bfe5f23904cffe
> Rebooting...
> ```

@nliaudat: Thanks for reporting this. I tested the same way and I also get the execption during OTA update from 14.0.3 to versions newer than 15.0.1 (rolling). It's not directly related to this PR but it seems it's related to new parameter documentation feature #2059 (or the neccessary new subfolder for this feature) which is in rolling and this PR is based on rolling. Workaround: Create the new subfolder in html manually before update or just copy the whole content of html SD card manually.

@caco3: I think I know what's the potential issue. It's related to the new subfolder param_tooltips in html which is not available when updating from 14.0.3. The firmware 14.0.3 is not able to create that new subfolder during OTA update. How could we handle this? In this case it would be mandatory to update first to 15.0.1 (because there updated function is included which is capable to create new folders) and then to newer versions / rolling.

**Comment by caco3** [comment]
I just fixed this in https://github.com/jomjol/AI-on-the-edge-device/pull/2080

**Comment by caco3** [comment]
firmwares >15.0 will automatically create the needed folders.
but I changed to use a flat folder structure in case somebody wants to upgrade from an older version

**Comment by caco3** [comment]
>  therefore roaming functioanlity is not acitvated right now

ah, that explains why it did not work in my tests. It still uses the farther away AP althrough my fritzbox is much closer. And it also explains https://github.com/jomjol/AI-on-the-edge-device/issues/1969

**Comment by Slider0007** [comment]
> I just fixed this in #2080

Wow, that was quick :-) Thanks!

**Comment by Slider0007** [comment]
> > * Based on this PR, provide an additional PR to fully implement wlan roaming function including related error handling.
> >   @jomjol: Working on this PR I figured out, that basic roaming functions are implemented, but sdkconfig and wifi config flags are not yet set, therefore roaming functioanlity is not acitvated right now. To activate roaming, enough heap needs to be provided first to prevent potential device crash (roaming needs at least 8-10kB additional heap which is not guaranteed in actual configuration). I'll provide an proposal, if it's ok for you.
> 
> I was not aware of this, so if you have an idea, how to guarantee the heap, we should enable it.

I did some reseach how to fully implement roaming with having heap usage in mind. After this PR is merged I provide a proposal with description (because it's based on this PR).

**Comment by Slider0007** [comment]
> @nliaudat: Thanks for reporting this. I tested the same way and I also get the execption during OTA update from 14.0.3 to versions newer than 15.0.1 (rolling). It's not directly related to this PR but it seems it's related to new parameter documentation feature #2059 (or the neccessary new subfolder for this feature) which is in rolling and this PR is based on rolling. Workaround: Create the new subfolder in html manually before update or just copy the whole content of html SD card manually.

@nliaudat: @caco3 was quick and fixed it already in the newest rolling, so no workaround necessary anymore. I updated and tested it already. Update from 14.0.3 to newest rolling or this PR is now working. You have to use lastest build https://github.com/jomjol/AI-on-the-edge-device/actions/runs/4271256448 to benefit.

**Pull request merged**
