### PR TITLE
Fix building with `-D DEBUG_DETAIL_ON`

### PR DESCRIPTION
**Pull request by slovdahl**
Building with `-D DEBUG_DETAIL_ON` has been broken since #3029.

### CODE REVIEW

**Comment by caco3** [comment]
What is the error message?
I think there is a better way than just remove those log messages.

**Comment by SybexX** [comment]
res and quality no longer exist as they have been replaced by CCstatus.ImageFrameSize and CCstatus.ImageQuality

**Comment by caco3** [comment]
Ah, ok, right

**Comment by caco3** [comment]
@slovdahl  Thanks for the Pull request!

**Pull request merged**
