### PR TITLE
updated OTA page

### PR DESCRIPTION
**Pull request by caco3**
- Made xhttp calls asynchroneous
- Added progress counter
- Removed reboot button, it is no longer needed
- Added note about not reloading/changing page

### CODE REVIEW

**Comment by haverland** [comment]
image
Upload in my case (update.zip) 1 minute

**Comment by haverland** [comment]
And after 3 minutes processing
image
open file /sdcard/firmware/firmware.bin in mode rb
File /sdcard/firmware/firmware.bin successfully opened
␛[0;32mI (485192) server_ota: New firmware version: aa72cab␛[0m
␛[0;32mI (485192) server_ota: Running firmware version: v11.4.4-29-g69a9271␛[0m
␛[0;32mI (493242) server_ota: esp_ota_begin succeeded␛[0m
␛[0;32mI (511672) server_ota: Total Write binary data length: 1887344␛[0m
␛[0;32mI (511672) esp_image: segment 0: paddr=001f0020 vaddr=3f400020 size=4df00h (319232) map␛[0m
␛[0;32mI (511802) esp_image: segment 1: paddr=0023df28 vaddr=3ffb0000 size=020f0h (  8432) ␛[0m
␛[0;32mI (511812) esp_image: segment 2: paddr=00240020 vaddr=400d0020 size=15e048h (1433672) map␛[0m
␛[0;32mI (512292) esp_image: segment 3: paddr=0039e070 vaddr=3ffb20f0 size=029c8h ( 10696) ␛[0m
␛[0;32mI (512322) esp_image: segment 4: paddr=003a0a40 vaddr=40080000 size=1c1f4h (115188) ␛[0m
␛[0;32mI (512372) esp_image: segment 5: paddr=003bcc3c vaddr=50000000 size=00010h (    16) ␛[0m
␛[0;32mI (512382) esp_image: segment 0: paddr=001f0020 vaddr=3f400020 size=4df00h (319232) map␛[0m
␛[0;32mI (512492) esp_image: segment 1: paddr=0023df28 vaddr=3ffb0000 size=020f0h (  8432) ␛[0m
␛[0;32mI (512512) esp_image: segment 2: paddr=00240020 vaddr=400d0020 size=15e048h (1433672) map␛[0m
␛[0;32mI (513002) esp_image: segment 3: paddr=0039e070 vaddr=3ffb20f0 size=029c8h ( 10696) ␛[0m
␛[0;32mI (513022) esp_image: segment 4: paddr=003a0a40 vaddr=40080000 size=1c1f4h (115188) ␛[0m
␛[0;32mI (513072) esp_image: segment 5: paddr=003bcc3c vaddr=50000000 size=00010h (    16) ␛[0m
␛[0;33mW (513132) httpd_txrx: httpd_sock_err: error in send : 113␛[0m
␛[0;33mW (513132) httpd_txrx: httpd_sock_err: error in send : 128␛[0m
Send reboot
␛[0;33mW (513132) httpd_txrx: httpd_sock_err: error in recv : 113␛[0m
␛[0;33mW (513142) httpd_txrx: httpd_sock_err: error in recv : 113␛[0m

**Comment by caco3** [comment]
Do you suggest to increase the estimated time or remove it completely?
On https://github.com/jomjol/AI-on-the-edge-device/pull/1099#issuecomment-1260081819, did it success or where there an error?

**Comment by haverland** [comment]
Increase the time.
Looks like it was successful, but the respond comes never back. Second try works.

**Pull request merged**
