### PR TITLE
*** OLD *** Migrate configuration -> Superseeded by PR2017

### PR DESCRIPTION
**Pull request by caco3**
Replaced by https://github.com/jomjol/AI-on-the-edge-device/pull/2017

---

This PR adds a migration function of some parameters:
- Rename section `MakeImage` to `TakeImage`, rename all variables and files accordingly
- Rename `Intervall` to `Interval`, rename all variables
- Rename `RSSIThreashold` to `RSSIThreshold`, rename all variables
- For all boolean parameters: If they where commented out -> remove the semicolon and set them to their default value (according to their C++ initialization).

The migration function gets called at startup and modifies the config file as needed. If one or mor eparameter needs a migration, store the `config.ini` as `config.bak` before any change to it.

# Yet to do
- [x] Remove the checkboxes for all boolean parameters in the UI -> @jomjol can you do this? I tried it but failed to understand how it exactly works.
- [ ] @jomjol @haverland @Slider0007: Are there other parameters where you think we should rename them? This PR might be a good time to do so.
- [ ] Testing

### CODE REVIEW

**Comment by jomjol** [comment]
> @jomjol @haverland @Slider0007: Are there other parameters where you think we should rename them? This PR might be a good time to do so.

I started to do so, but as the categories are renamed as well, I could not fully test. Will do this in the next days.

**Comment by caco3** [comment]
@jomjol You should start with the `sd-card/html/edit_config_param.html` from this branch, I updated the section/parameters already

**Comment by caco3** [comment]
@jomjol There was a merge conflict, so I solved it, see https://github.com/jomjol/AI-on-the-edge-device/pull/2001/commits/d1d2d67880be2ddb347d8c18674e8e5dfd9680cd

Not sure if I now reverted some of your work!

**Comment by jomjol** [comment]
> @jomjol There was a merge conflict, so I solved it, see [d1d2d67](https://github.com/jomjol/AI-on-the-edge-device/commit/d1d2d67880be2ddb347d8c18674e8e5dfd9680cd)
> 
> Not sure if I now reverted some of your work!

I think I just corrected it.

**Comment by Slider0007** [comment]
@caco3: Some discussion topics:

config.ini:
`AutoAdjustSummertime` --> AFAIK this not used anymore
`LogfileRetentionInDays` --> maybe `LogRetentionPeriod` (specially for logging the images, Logfile... is kind of misleading, but renaming this is not a must)
`SetRetainFlag` --> `RetainFlag` or `RetainMessages`(renaming not a must)

**Comment by caco3** [comment]
> config.ini: `AutoAdjustSummertime` 

Stimmt, das wird in der Firmware nirgends mehr verwendet. @jomjol, können wir das löschen?

> LogfileRetentionInDays --> maybe LogRetentionPeriod (specially for logging the images, Logfile... is kind of misleading, but renaming this is not a must)

Right.
I would suggest to do it as following:
- Analog/Digits: Here we use it for the training images. I would rename it to `RoiImagesRetentionInDays` or `TrainingImagesRetentionInDays`. And I would rename the related parameters as well. Ans also update the default path (eg. `/log/analog`)
- Debug: Keep `LogfileRetentionInDays` as is. 

> `SetRetainFlag` --> `RetainFlag` or `RetainMessages`(renaming not a must)

I would go for `RetainMessages`

@jomjol, what is `LogImageLocation` in the section `TakeImage` used for? Is that storning the whole cam image?

**Comment by jomjol** [comment]
> > config.ini: `AutoAdjustSummertime`
> 
> Stimmt, das wird in der Firmware nirgends mehr verwendet. @jomjol, können wir das löschen?

Right, we can delete it


> > LogfileRetentionInDays --> maybe LogRetentionPeriod (specially for logging the images, Logfile... is kind of misleading, but renaming this is not a must)
> 
> Right. I would suggest to do it as following:
> 
>     * Analog/Digits: Here we use it for the training images. I would rename it to `RoiImagesRetentionInDays` or `TrainingImagesRetentionInDays`. And I would rename the related parameters as well. Ans also update the default path (eg. `/log/analog`)
TrainingImagesRetention... could make the people think, the device is training itself. Therefore I would go for "ROIImages..."


> @jomjol, what is `LogImageLocation` in the section `TakeImage` used for? Is that storning the whole cam image?

This is used for storing the full images (before cutting) in the directory `/log/source`

**Comment by caco3** [comment]
I think we should to a release 14.1 which just the parameter migration.
Release 15 will have a lot of changes which might break stuff. And this way users can go back top v14 without broken parameters.

I will prepare a branch for it.

**Comment by caco3** [comment]
New PR which **only** contains the parameter changes: https://github.com/jomjol/AI-on-the-edge-device/pull/2017/

**Pull request closed without merging**
