### PR TITLE
ATA-Trim support

### PR DESCRIPTION
**Pull request by SybexX**
copied the ESP IDF component fatfs to our project and modified it to:
1.  SD initialize -> read SD parameters -> if FF_USE_TRIM = 1 -> ATA-Trim is supported -> run through ATA-Trim routine
2.  SD initialize -> read SD parameters -> if FF_USE_TRIM = 1 -> ATA-Trim is not supported -> do nothing
3.  SD initialize -> read SD parameters -> if FF_USE_TRIM = 0 -> do nothing

Original (official ESP-IDF behaviour):
1.  SD initialize -> read SD parameters -> if FF_USE_TRIM = 1 -> no matter whether ATA-Trim is supported or not -> run through ATA-Trim routine
3.  SD initialize -> read SD parameters -> if FF_USE_TRIM = 0 -> do nothing

See https://github.com/jomjol/AI-on-the-edge-device/discussions/2710 for details

### CODE REVIEW

**Comment by jomjol** [comment]
Is this doing the same as: https://github.com/jomjol/AI-on-the-edge-device/pull/2779 ???

@SybexX  and @caco3:

My question: one or the other pull request or both?

**Comment by SybexX** [comment]
Yes, only I have now adapted fatfs and sdmmc from the ESP-IDF so that FF_USE_TRIM can remain at 1 and cards that support it can also use it.

**Comment by caco3** [comment]
@jomjol Yes, the other PR was the initial one, but we should go with the one here as it is advanced.
@SybexX Can you please in the readme and in the code mark your changes? This makes it easier when we want to update the file sin the future.

I updated the PR description with your nice explanation.

@friedpa and @Rak3tenmann Can you also test this PR and check it works for you?
Get the build from  here: https://github.com/jomjol/AI-on-the-edge-device/actions?query=event%3Apull_request (use the latest `[SybexX:ATA_TRIM_SUPPORT](https://github.com/SybexX/AI-on-the-edge-device/tree/ATA_TRIM_SUPPORT)` build)

**Comment by friedpa** [comment]
Good Afternoon Gents,
the AI-on-the-edge-device__update__2781_merge_(9a3f3de) works as tested before.
Happy new year!

**Comment by caco3** [comment]
Thanks @SybexX for your contribution!

**Comment by SybexX** [comment]
Since this problem really affects all 5. versions, I have now created a "Issues" in espressif, let's see if something happens there.

https://github.com/espressif/esp-idf/issues/12912

**Comment by olegarch** [comment]
Linker complains about duplicates:

packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio/build/esp32cam/esp-idf/esp-sdmmc/libesp-sdmmc.a(sdmmc_common_mh.o): in function `sdmmc_init_ocr':
AI-on-the-edge-device\code/components\esp-sdmmc/sdmmc_common_mh.c:25: multiple definition of `sdmmc_init_ocr'; .pio/build/esp32cam/esp-idf/sdmmc/libsdmmc.a(sdmmc_common.o):C:\Users\olegk\.platformio\packages\framework-espidf\components\sdmmc/sdmmc_common.c:23: first defined here

**Comment by SybexX** [comment]
@olegarch I also use Windows and had this problem
A workaround for me was to make the following change in platformio.ini:

```c
; The main env - default
[env:esp32cam]
extends = common:esp32-idf
board = esp32cam
framework = espidf
lib_ignore = sdmmc, fatfs					// <<<<<<<<<<<<<<<<<<<<< ++++
build_flags = 
    ; ### common imported : 
    ${common:esp32-idf.build_flags}
	${flags:runtime.build_flags}
    ; ### Sofware options : (can be set in defines.h)
	-D ENABLE_MQTT 
    -D ENABLE_INFLUXDB 
    -D ENABLE_SOFTAP 
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
```

**Pull request merged**
