### PR TITLE
Migrated parameters

### PR DESCRIPTION
**Pull request by caco3**
replaced by https://github.com/jomjol/AI-on-the-edge-device/pull/2023

### CODE REVIEW

**Comment by Slider0007** [comment]
@caco3, @jomjol: Some more discussion points in terms of config parameters:

`main.ExtendedResolution` in section `[ANALOG]`
--> Couldn't find in software

`TimeServer` = pool.ntp.org
--> I would remove the checkbox, because disabled parameter does not mean that service is disabled. Actual logic only disables timeservice when input field is empty.

`Hostname` = watermeter
--> I would remove the checkbox and set the default value (watermeter; to be aligned with logic). Disabling the parameter does nothing with actual logic (internally, default name is used anyway).

`RSSIThreashold` = 0
--> I would remove the checkbox, because function gets disabled with input = 0 and in my opinion there is no benefit to disable parameter additionally. It's hidden in expert anyway.

##############################
Defaults of parameters:
`CNNGoodThreshold` --> I would disable this by default, because it's experimental and only used for some models.
`InitialRotate` = 179 -> Default: 0?

`main.MaxRateValue` = 0.05
`;main.MaxRateType` = AbsoluteChange
--> MaxRateValue is enabled by default and MaxRateType is disabled? Is this by purpose? (AbsolutChange is default internally)

**Comment by Slider0007** [comment]
@caco3: Having an additional parameter adpation logic in firmware we have now two locations were parameters are adapted for migration/compability reason.
Just for my understanding: In future what will be handled in JS (readconfigparam.js) and what handled in directly firmware?

**Comment by caco3** [comment]
What do you mean with "additional parameter adpation logic in firmware"? I only added function to migrate the parameters. and it works on the plain text file.
Beside of this, change of boolean parameters and all the renaming, nothing should have changed.

**Comment by Slider0007** [comment]
> What do you mean with "additional parameter adpation logic in firmware"? I only added function to migrate the parameters. and it works on the plain text file. Beside of this, change of boolean parameters and all the renaming, nothing should have changed.

I mean your migrate function. I was just thinking about this compabilty part in readconfigparam.js were parameters are also e.g. renamed and partly modified due to compability reason.

**Comment by caco3** [comment]
> > What do you mean with "additional parameter adpation logic in firmware"? I only added function to migrate the parameters. and it works on the plain text file. Beside of this, change of boolean parameters and all the renaming, nothing should have changed.
> 
> I mean your migrate function. I was just thinking about this compabilty part in readconfigparam.js were parameters are also e.g. renamed and partly modified due to compability reason.

The whole migration happens in the migration function in the firmware.
The rest of the firmware and Web UI only adapt the changed names.
The Web UI does not rename anything!

**Comment by Slider0007** [comment]
> > > What do you mean with "additional parameter adpation logic in firmware"? I only added function to migrate the parameters. and it works on the plain text file. Beside of this, change of boolean parameters and all the renaming, nothing should have changed.
> > 
> > 
> > I mean your migrate function. I was just thinking about this compabilty part in readconfigparam.js were parameters are also e.g. renamed and partly modified due to compability reason.
> 
> The whole migration happens in the migration function in the firmware. The rest of the firmware and Web UI only adapt the changed names. The Web UI does not rename anything!

Here and in the following lines some parameters are "modified" due to compability reason: 
https://github.com/jomjol/AI-on-the-edge-device/blob/44e186e65ba7fa093a4b787728ebc0778c3398ea/sd-card/html/readconfigparam.js#L289

Maybe @jomjol can tell more to this.

**Comment by caco3** [comment]
To simplify the PR, I only do the renaming in this PR. 
The change of paths and migration of commented out boolean to enabled params with default will be done separately.

**Comment by caco3** [comment]
@Slider0007 Thanks for thinking into it!

> `main.ExtendedResolution` in section `[ANALOG]` --> Couldn't find in software

Removed now (its only used in `[PostProcessing]`)

> `TimeServer` = pool.ntp.org --> I would remove the checkbox, because disabled parameter does not mean that service is disabled. Actual logic only disables timeservice when input field is empty.

Let's do that later to keep it as simple as possible.
 
> `Hostname` = watermeter --> I would remove the checkbox and set the default value (watermeter; to be aligned with logic). Disabling the parameter does nothing with actual logic (internally, default name is used anyway).

Let's do that later to keep it as simple as possible. Also I would remove `water` from the default value.

> `RSSIThreashold` = 0 --> I would remove the checkbox, because function gets disabled with input = 0 and in my opinion there is no benefit to disable parameter additionally. It's hidden in expert anyway.

Let's do that later to keep it as simple as possible.

> Defaults of parameters: `CNNGoodThreshold` --> I would disable this by default, because it's experimental and only used for some models. `InitialRotate` = 179 -> Default: 0?

@jomjol What do you think? The default in the firmware seems to be `0.0`!

> main.MaxRateValue = 0.05 ;
> main.MaxRateType = AbsoluteChange --> MaxRateValue is enabled by default and MaxRateType is disabled? Is this by purpose? (AbsolutChange is default internally)

@jomjol ?

**Comment by caco3** [comment]
> > > > What do you mean with "additional parameter adpation logic in firmware"? I only added function to migrate the parameters. and it works on the plain text file. Beside of this, change of boolean parameters and all the renaming, nothing should have changed.
> > > 
> > > 
> > > I mean your migrate function. I was just thinking about this compabilty part in readconfigparam.js were parameters are also e.g. renamed and partly modified due to compability reason.
> > 
> > 
> > The whole migration happens in the migration function in the firmware. The rest of the firmware and Web UI only adapt the changed names. The Web UI does not rename anything!
> 
> Here and in the following lines some parameters are "modified" due to compability reason:
> 
> https://github.com/jomjol/AI-on-the-edge-device/blob/44e186e65ba7fa093a4b787728ebc0778c3398ea/sd-card/html/readconfigparam.js#L289
> 
> Maybe @jomjol can tell more to this.

That is old code, not sure if we still need it but I would keep it as is for now to keep the PR as simple as possible.

**Comment by caco3** [comment]
As far as I tested, it should be complete now.
But I had to create another PR for this as I accidentally included the InfluxDB2 stuff.
How ever I really only want to have the parameter migration contained.

Please review and test https://github.com/jomjol/AI-on-the-edge-device/pull/2023

**Pull request closed without merging**
