### PR TITLE
new model dig-class_0165_s2 on new images

### PR DESCRIPTION
**Pull request by haverland**

### CODE REVIEW

**Comment by nliaudat** [comment]
I have better results with 160 version

With 165 version sometimes :
6 => 9 and 9 =>6 
3 => 8 and 8 => 3

The errors are alway on red digits. 
You you want I cap pictures for next release ?

Regards
Nicolas

**Comment by haverland** [comment]
Hi Nicolas,

the latest release hat dig-class100-0167. Could you try it?.

But if 160 is fine for you, where is no really need to change it. Mostly I got only new images. 

in case of 165 to 166 I changed the optimization (make a lite model) a bit, because not every model performs after shrinking the model.

**Comment by nliaudat** [comment]
I cannot find dig-class100-0167 in "AI-on-the-edge-device__update__v15.3.0" nor in "Tenth-of-step-of-a-meter-digit-1.6.1"
Regards

**Comment by haverland** [comment]
Is in current master (15.3.0) https://github.com/jomjol/AI-on-the-edge-device/tree/rolling/sd-card/config

and came with https://github.com/jomjol/AI-on-the-edge-device/pull/2545 that is part of 15.3.0.

**Comment by nliaudat** [comment]
> Is in current master (15.3.0) https://github.com/jomjol/AI-on-the-edge-device/tree/rolling/sd-card/config
> 
> and came with #2545 that is part of 15.3.0.

Many thanks ! 
I am in release: v15.3.0 (Commit: 3fbff0a), but the 167 model was not upgraded. 
I upload it manually and test. 
Regards

**Pull request merged**
