### PR TITLE
sdkconfig optimization #1577

### PR DESCRIPTION
**Pull request by nliaudat**
RAM:   [==        ]  19.2% (used 63016 bytes from 327680 bytes)
Flash: [========  ]  78.3% (used 1522617 bytes from 1945600 bytes)

### CODE REVIEW

**Comment by jomjol** [comment]
The change is so big, that we should test it in a dedicated path.
1)  This would make 1 device in my home not working anymore:
```
#may trouble very old esp-cam version (work with Chip is ESP32-D0WDQ6 (revision 1))
ESP32_REV_MIN_3=y
CONFIG_ESP32_REV_MIN_3=y 
```

2) I have no idea, what happens, if we disable all debugging and logging
I have no time currently to test and verfy this changes.
3) Currently we do not need addiational space, as there are no big features planned to be implemented. Why should we change?

@caco3 @haverland what is your opinion?

**Comment by nliaudat** [comment]
Hi, 

The disabled logging feature are only esp-cam (aka esp32) logs. All we need as logging is after boot and we do not mind the esp-cam corre

I need more space to implement Matter protocol. :)

You are right with needing a separate dev branch. I mean it must be tested on many devices before release.
I have 1 test device and 2 in production and all pass firmware upgrade, but I seen differences between VS studio compile (use sdkconfig.defauts) and `pio run --target upload` (use skkconfig.esp32cam)

I'll check with the compile version of github if you explain me how to retrieve the binaries or update.zip from the pull request (update__1598_merge_(cb846c7))

Regards

**Comment by caco3** [comment]
@nliaudat You can fetch the auto build from https://github.com/jomjol/AI-on-the-edge-device/actions Just select the right branch, then fetch the update_*.zip. Optionally extract the firmware.bin and just flash that one.

**Comment by caco3** [comment]
I would suggest that we work on the currently open bugs and create another release (13.0.x or 13.1.x.)

Then create a separate branch and play with those optimizations.
Since we have auto build we eg. could have a `rolling-optimized-flash-usage` and periodically merge `rolling` into it.

**Comment by jomjol** [comment]
@caco3 : good idea to have a parallel branch with optimized flash size.

**Comment by nliaudat** [comment]
I confirm the devices are more responsive. I mean due to : 

CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y
CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y
SPIRAM_SPEED_80M=y

Thanks to create new branch
Regards

**Comment by caco3** [comment]
> CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y
> CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240

Oh, wow!
@jomjol Is there a reason we do not use it with max speed? (eg. stability)

**Comment by jomjol** [comment]
In the past some device were much more stable with a lower processor speed.

**Comment by caco3** [comment]
maybe we could make it configurable?

Most will want to have a better responsiveness. And if it is not stable (low hardware quality), they can go to slower again.

**Pull request closed without merging**
