### PR TITLE
date for graph is now selectable

### PR DESCRIPTION
**Pull request by rdmueller**
another update for the graph feature

### CODE REVIEW

**Comment by jomjol** [comment]
@rdmueller: there is no a much simpler data format availalbe.
After installing the current rolling, you find in `/log/data` a textfile, that contains only the measurement values (raw, value, prevalue, rate rel, rate abs, read out cnn-numbers). 
This has much more data, than the logfile and is much easier to parse.

**Comment by jomjol** [comment]
@rdmueller: I just adapted the code to data - very easy - GREAT!

View things open:
- in multi number counters (e.g. HT & NT), one would need to select for this as well.
- would be great to know, which data is available, so load all available data files into the preselect.
- there are now also other values available, e.g. rate (abs or relativ) --> could also be selectable

let's see, if I find time to implement a bit of this

**Comment by rdmueller** [comment]
Great to hear that you like this feature.
I hope I can find some time to address those missing features.
Would be great if you could tag your repo or at least my PRs for hacktoberfest 😀

**Comment by jomjol** [comment]
I'm not in the topic hacktoberfest and honestly have no idea, what it is about, and what happens with this.
We have so many mails and request, that I'm not searching for another source of input.

I'm already working on the integration of several numbers and a list of available datas

**Comment by rdmueller** [comment]
@caco3 thanx for adding the label!

**Pull request merged**
