### PR TITLE
revert submodule esp32-camera to commit used in v15.3.0

### PR DESCRIPTION
**Pull request by caco3**
Submodules in rolling:
```
Submodul-Pfad 'code/components/esp-nn': '34e97138de6e80ab6e047262c1c8b77514739a39' ausgecheckt
Submodul-Pfad 'code/components/esp32-camera': 'dba8da9898928d9808d57a0b0cdcde9f130ed8fe' ausgecheckt
Submodul-Pfad 'code/components/stb': '5736b15f7ea0ffb08dd38af21067c314d6a3aae9' ausgecheckt

Submodul-Pfad 'code/components/esp-tflite-micro': '13f26b829405e9323e4212ffa954c261b1e21eeb' ausgecheckt
```

Submodules in v15.3.0:
```
Submodul-Pfad 'code/components/esp-nn': '6b3ef8e226a05554a6d874f6456f5ca1771c01c2' ausgecheckt
Submodul-Pfad 'code/components/esp32-camera': '5c8349f4cf169c8a61283e0da9b8cff10994d3f3' ausgecheckt
Submodul-Pfad 'code/components/stb': '5736b15f7ea0ffb08dd38af21067c314d6a3aae9' ausgecheckt

Submodul-Pfad 'code/components/tflite-micro-esp-examples': '095f55a6ee0b9d51f59a7a05d405df2e6336c178' ausgecheckt
```

- [x] `stb` did not get updated -> no issue
- [x] `esp32-camera`  could get reverted -> needs checking if issue was here.
- [ ] `esp-nn` can not be easily reverted due to `ERROR: Cannot process component requirements.  Multiple candidates to
  satisfy project requirements: requirement: "esp-nn" candidates: "espressif__esp-nn, esp-nn"`
- [ ] `tflite-micro-esp-examples` got restructured and is now called `esp-tflite-micro` -> revertion needs some extra work

### CODE REVIEW

**Comment by caco3** [comment]
Reverting `esp32-camera` did not fix the issue:
grafik

**Comment by caco3** [comment]
I am unable to revert the submodules (build errors).
Therefore I tried another approach, see https://github.com/jomjol/AI-on-the-edge-device/pull/2838/

**Comment by friedpa** [comment]
What was the problem?

**Comment by caco3** [comment]
I know now that it is not due to the submodule updates, so this PR no longer is needed.

**Pull request closed without merging**
