### PR TITLE
get before set preValue in PostProcessing-Flow

### LINKED ISSUE #2064: "Previous value" same as "value" even if there is a change
### The Problem

I think the preValue in the datalog and in the mqtt json-message is broken. 

As you can see in my data-log appended below, the counter was continuosly increasing during the timeframe. Each entry has a positive rate and there are no detection errors inbetween. BUT all three values per line are the same. I would expect to see two identical numbers/strings (value and raw) and one number that is the same as the line above (prevalue) 

```
2023-02-22T05:29:13+0100,main,11063.93,11063.93,11063.93,0.008219,0.04,no error,1.0,1.0,0.0,6.0,3.0,9.0,2.6
2023-02-22T05:34:04+0100,main,11064.02,11064.02,11064.02,0.018557,0.09,no error,1.0,1.0,0.0,6.0,4.0,0.0,2.0
2023-02-22T05:38:54+0100,main,11064.13,11064.13,11064.13,0.022759,0.11,no error,1.0,1.0,10.0,6.0,4.0,1.0,3.0
2023-02-22T05:43:46+0100,main,11064.24,11064.24,11064.24,0.022603,0.11,no error,1.0,0.9,10.0,6.0,4.0,2.0,4.0
2023-02-22T05:48:36+0100,main,11064.34,11064.34,11064.34,0.020690,0.10,no error,1.0,1.0,10.0,6.0,4.0,3.0,4.0
2023-02-22T05:53:28+0100,main,11064.45,11064.45,11064.45,0.022603,0.11,no error,1.0,0.9,10.0,6.0,4.0,4.0,5.0
2023-02-22T05:58:18+0100,main,11064.55,11064.55,11064.55,0.020690,0.10,no error,1.0,1.0,0.0,6.0,4.0,5.0,5.0
2023-02-22T06:03:10+0100,main,11064.83,11064.83,11064.83,0.057534,0.28,no error,1.0,0.9,0.0,6.0,4.0,8.0,3.0
2023-02-22T06:08:00+0100,main,11064.84,11064.84,11064.84,0.002069,0.01,no error,1.0,0.9,10.0,6.0,4.0,8.0,4.0 
```

I have the suspicion that it might be related to code in `code/components/jomjol_flowcontroll/ClassFlowPostProcessing.cpp` around lines 904 -912. Here the preValue gets reset to value (906) before the ReturnPreValue is build by rounding the preValue. 

Unfortunately my fork is not jet building, but I will try to provide a patch. 

Logfile below is from the following measurements:
```
2023-02-22T22:36:33+0100,main,11064.87,11064.87,11064.87,0.000000,0.00,no error,1.0,0.9,10.0,6.0,4.0,8.0,7.0
2023-02-22T22:41:13+0100,main,11064.90,11064.90,11064.90,0.006429,0.03,no error,1.0,0.9,10.0,6.0,4.0,8.9,10.0
2023-02-22T22:46:04+0100,main,11064.98,11064.98,11064.98,0.016495,0.08,no error,1.0,0.9,10.0,6.0,4.0,9.0,8.0 
```

### Version

v14.0.3 (Commit: 6c891ab+)

### Logfile

```shell
0d00h10m00s] 2023-02-22T22:45:55	<DBG>	[TFLITE SERVER] ----------------------------------------------------------------
[0d00h10m00s] 2023-02-22T22:45:55	<INF>	[TFLITE SERVER] Round #3 started
[0d00h10m00s] 2023-02-22T22:45:55	<DBG>	[MQTT IF] Published topic: gas/status, content: Take Image (msg_id=31)
[0d00h10m11s] 2023-02-22T22:46:06	<DBG>	[MQTT IF] Published topic: gas/status, content: Aligning (msg_id=32)
[0d00h10m36s] 2023-02-22T22:46:30	<DBG>	[MQTT IF] Published topic: gas/status, content: Digitalization of ROIs (msg_id=33)
[0d00h10m36s] 2023-02-22T22:46:30	<DBG>	[CNN] doFlow after alignment
[0d00h10m36s] 2023-02-22T22:46:31	<DBG>	[TFLITE] CTfLiteClass::LoadModel
[0d00h10m36s] 2023-02-22T22:46:31	<DBG>	[TFLITE] CTfLiteClass::ReadFileToModel: /sdcard/config/dig-cont_0570_s3.tflite
[0d00h10m39s] 2023-02-22T22:46:33	<DBG>	[TFLITE] CTfLiteClass::MakeAllocate
[0d00h10m39s] 2023-02-22T22:46:33	<DBG>	[CNN] Processing Number 'main'
[0d00h10m39s] 2023-02-22T22:46:33	<DBG>	[CNN] ROI #0 - TfLite
[0d00h10m39s] 2023-02-22T22:46:33	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h10m44s] 2023-02-22T22:46:38	<DBG>	[CNN] After Invoke
[0d00h10m44s] 2023-02-22T22:46:38	<DBG>	[CNN] _num (p, m): 1 2 0 _val (p, m): 0.982216 0.013526 0.003512 result: 1.013584 _fit: 0.995742
[0d00h10m44s] 2023-02-22T22:46:38	<DBG>	[CNN] ROI #1 - TfLite
[0d00h10m44s] 2023-02-22T22:46:38	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h10m49s] 2023-02-22T22:46:43	<DBG>	[CNN] After Invoke
[0d00h10m49s] 2023-02-22T22:46:43	<DBG>	[CNN] _num (p, m): 1 2 0 _val (p, m): 0.931127 0.005181 0.055806 result: 0.943455 _fit: 0.986933
[0d00h10m49s] 2023-02-22T22:46:44	<DBG>	[CNN] ROI #2 - TfLite
[0d00h10m49s] 2023-02-22T22:46:44	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h10m54s] 2023-02-22T22:46:49	<DBG>	[CNN] After Invoke
[0d00h10m54s] 2023-02-22T22:46:49	<DBG>	[CNN] _num (p, m): 0 1 9 _val (p, m): 0.997284 0.000550 0.002167 result: 9.997832 _fit: 0.999450
[0d00h10m54s] 2023-02-22T22:46:49	<DBG>	[CNN] ROI #3 - TfLite
[0d00h10m54s] 2023-02-22T22:46:49	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h10m59s] 2023-02-22T22:46:54	<DBG>	[CNN] After Invoke
[0d00h10m59s] 2023-02-22T22:46:54	<DBG>	[CNN] _num (p, m): 6 7 5 _val (p, m): 0.973410 0.001032 0.000004 result: 6.001059 _fit: 0.974442
[0d00h10m59s] 2023-02-22T22:46:54	<DBG>	[CNN] ROI #4 - TfLite
[0d00h10m59s] 2023-02-22T22:46:54	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h11m04s] 2023-02-22T22:46:59	<DBG>	[CNN] After Invoke
[0d00h11m04s] 2023-02-22T22:46:59	<DBG>	[CNN] _num (p, m): 4 5 3 _val (p, m): 0.999686 0.000312 0.000003 result: 4.000312 _fit: 0.999997
[0d00h11m05s] 2023-02-22T22:46:59	<DBG>	[CNN] ROI #5 - TfLite
[0d00h11m05s] 2023-02-22T22:46:59	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h11m10s] 2023-02-22T22:47:04	<DBG>	[CNN] After Invoke
[0d00h11m10s] 2023-02-22T22:47:04	<DBG>	[CNN] _num (p, m): 9 0 8 _val (p, m): 0.997752 0.002091 0.000157 result: 9.002091 _fit: 0.999843
[0d00h11m10s] 2023-02-22T22:47:04	<DBG>	[CNN] ROI #6 - TfLite
[0d00h11m10s] 2023-02-22T22:47:04	<DBG>	[CNN] CNN Type: DoubleHyprid10
[0d00h11m15s] 2023-02-22T22:47:09	<DBG>	[CNN] After Invoke
[0d00h11m15s] 2023-02-22T22:47:09	<DBG>	[CNN] _num (p, m): 8 9 7 _val (p, m): 0.999728 0.000249 0.000022 result: 8.000249 _fit: 0.999977
[0d00h11m15s] 2023-02-22T22:47:09	<DBG>	[MQTT IF] Published topic: gas/status, content: Post-Processing (msg_id=34)
[0d00h11m15s] 2023-02-22T22:47:09	<DBG>	[CNN] getReadout _analog=0, _extendedResolution=0, prev=-1
[0d00h11m15s] 2023-02-22T22:47:09	<DBG>	[CNN] PointerEvalHybridNew - No predecessor - Result = 8 number: 8.000249 number_of_predecessors = -1.000000 eval_predecessors = -1 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout(dig100)  prev=8
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 9 number: 9.002091 number_of_predecessors = 8.000249 eval_predecessors = 8 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 9
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 98
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 4 number: 4.000312 number_of_predecessors = 9.002091 eval_predecessors = 9 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 4
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 498
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 6 number: 6.001059 number_of_predecessors = 4.000312 eval_predecessors = 4 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 6
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 6498
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 0 number: 9.997832 number_of_predecessors = 6.001059 eval_predecessors = 6 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 0
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 06498
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, zero crossing has taken placen = 1 number: 0.943455 number_of_predecessors = 9.997832 eval_predecessors = 0 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 1
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 106498
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 1 number: 1.013584 number_of_predecessors = 0.943455 eval_predecessors = 1 Digital_Uncertainty = 0.200000
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#PointerEvalHybridNew()= 1
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[CNN] getReadout#result= 1106498
[0d00h11m15s] 2023-02-22T22:47:10	<INF>	[POSTPROC] main: Raw: 11064.98, Value: 11064.98, Status: no error
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/status, content: Sending MQTT (msg_id=35)
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[MQTT SERVER] Publishing system MQTT topics...
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/uptime, content: 675 (msg_id=36)
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/freeMem, content: 2984914 (msg_id=37)
[0d00h11m15s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/wifiRSSI, content: -50 (msg_id=38)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/CPUtemp, content: 55 (msg_id=39)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT] Publishing MQTT topics...
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/value, content: 11064.98 (msg_id=40)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/error, content: no error (msg_id=41)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/rate, content: 0.016495 (msg_id=42)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/rate_per_time_unit, content: 0.016495 (msg_id=43)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/changeabsolut, content: 0.08 (msg_id=44)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/rate_per_digitalization_round, content: 0.08 (msg_id=45)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/raw, content: 11064.98 (msg_id=46)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/timestamp, content: 2023-02-22T22:46:04+0100 (msg_id=47)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/main/json, content:   {     "value": "11064.98",     "raw": "11064.98",     "pre": "11064.98",     ".. (msg_id=48)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[MQTT IF] Published topic: gas/status, content: Flow finished (msg_id=49)
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[TFLITE SERVER] CPU Temperature: 56Â°C
[0d00h11m16s] 2023-02-22T22:47:10	<DBG>	[TFLITE SERVER] WIFI Signal (RSSI): -51dBm
[0d00h11m16s] 2023-02-22T22:47:10	<INF>	[TFLITE SERVER] Round #3 completed (76 seconds)
```

### Expected Behavior

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lukasHD**
fixes #2064

### CODE REVIEW

**Comment by lukasHD** [comment]
This commit moves 
`NUMBERS[j]->ReturnPreValue = RundeOutput(NUMBERS[j]->PreValue, NUMBERS[j]->Nachkomma);`
before the RE-set of preValue
`NUMBERS[j]->PreValue = NUMBERS[j]->Value;`

from the code I cannot see any side-effects

**Comment by lukasHD** [comment]
Output shows the correct values in the Data-File
```
2023-02-22T23:48:18+0100,main,11065.23,11065.23,11065.22,0.002490,0.01,no error,1.0,0.9,10.0,6.0,5.0,2.0,3.0
2023-02-22T23:52:59+0100,main,11065.29,11065.29,11065.23,0.012811,0.06,no error,1.0,1.0,0.0,6.0,5.0,2.0,9.0 
```

**Comment by lukasHD** [comment]
I also manually checked that the pre value in the json in the main MQTT Toic is now correct as well

**Comment by jomjol** [comment]
This change is not recommended. Maybe the word "PreValue" is a bit misleading. The content of this variable is the last valid value.
At that point of code, that you want to change, the new value is accepted as a valid value.
Therefore the PreValue is aequivalent to the value. This would be changed by your modification.

**Pull request closed without merging**
