### PR TITLE
Code translation

### PR DESCRIPTION
**Pull request by nliaudat**
Discussed in https://github.com/jomjol/AI-on-the-edge-device/pull/1604

Partial, not every function is done

### CODE REVIEW

**Comment by caco3** [comment]
This Pull Request does far more than it should have done!
I think we agreed that it only should contain translations and renaming, but it also contains changes to `sdkconfig.defaults` and `platformio.ini`!

I am going to manuall revert those files as we do not want to have that yet in `rolling`!

@jomjol @nliaudat @Slider0007 FYI

**Comment by nliaudat** [comment]
Sorry, my fault.

I am an old guy who do not master git cherry-pick :(

My bad

I wanted to revert now as I see yours.
Many thanks and another time very sorry.

Regards

**Comment by caco3** [comment]
No problem! We also should have checked better before merging.

Thanks for your contributions!

**Comment by jomjol** [comment]
@caco3, @nliaudat : that was my fault :-(. Sorry for the extra work

@caco3 : thanks for correcting!

**Pull request merged**
