### PR TITLE
Homeassistant discovery improvements

### PR DESCRIPTION
**Pull request by joshelboy**

### CODE REVIEW

**Comment by joshelboy** [comment]
Whoops thought i was in my fork

**Comment by caco3** [comment]
no problem!

What would you like to have changed?

**Comment by joshelboy** [comment]
Nothing really, I was messing around and trying to build myself a Firmware out of the two branches (in my local fork). I just couldn't wait until the >12.0.1 release for HASS discover ;). I usually am using git over CLI, so I was a bit confused when I noticed, that GitHub auto-selected the main repository lol. Thanks anyway!

**Comment by caco3** [comment]
ah, ok :)

you could try the latest build from rolling: https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Arolling

I am happy to get another feedback before the release.

**Pull request closed without merging**
