### PR TITLE
revert to setting lastvalue in only success case

### PR DESCRIPTION
**Pull request by dockSquadron**
fixes bug #2505

### CODE REVIEW

**Comment by Slider0007** [comment]
Be careful: Lastvalue timestamp is also used for data logging faeture. Reverting this only back will distort data logging feature (Multiple lines with same timestamp from last successful reading whenever a "bad" reading is logged).

In my opinion two separate timestamps are necessary, one for data logging feature to ensure growing timestamps for every reading and one for your need which is only updated on succesful reading.

**Comment by caco3** [comment]
@Slider0007 What do you think? Nobody else has an issue with it. And as you say, it changes the behaviour,  so I would **not** merge it.

**Comment by Slider0007** [comment]
> @Slider0007 What do you think? Nobody else has an issue with it. And as you say, it changes the behaviour, so I would **not** merge it.

@caco3: In my opinion, this change is necessary to fulfill the 'self-healing' feature of `Rate too high` with the `RateChange` setting, so it is correct in principle. However, the PR would have to be extended to solve both related topics. If only this PR gets merged, the problem of data logging would be open again, which was already addressed in #1839. Therefore, I would suggest using two timestamps for the contrary purposes of 'Max Rate Check purpose' (update timepstamp only on a valid reading) and 'Data Logging purpose' (update timestamp on every cycle).

**Comment by SybexX** [comment]
is fixed: https://github.com/jomjol/AI-on-the-edge-device/commit/f8eb4db171c718063812c14eb58fbdb7b1ae60d3

**Comment by caco3** [comment]
> is fixed: [f8eb4db](https://github.com/jomjol/AI-on-the-edge-device/commit/f8eb4db171c718063812c14eb58fbdb7b1ae60d3)

Does that mean the issue got solved in https://github.com/jomjol/AI-on-the-edge-device/pull/3180 and we can close this PR without further work?

**Comment by SybexX** [comment]
Yes, exactly and @Slider0007's concerns were also taken into account/incorporated.

**Pull request closed without merging**
