### PR TITLE
homeassistant service discovery: derive node_id when using nested topics

### LINKED ISSUE #1792: Allow finer granularization with MQTT topic structure (Homeassistant auto-discovery)
### The Problem

Hi,

Momentan habe ich das Problem, das wenn ich meine Wasseruhr in die bereits Vorhandene MQTT Struktur einbinden möchte, diese ist nach dem Muster "Home/Raum/Gerät" nach einer Empfehlung von MQTT aufgebaut, das damit dann die Homeassistant Auto-Discovery kaputt geht. Da der Konfigparameter Main Topic in die Home Assistant Struktur gerendert wird.
Man könnte das z.B Aufteilen in DNS Name + MainTopic und nimmt für die Homeassistant Discovery nur den DNS Name oder so.
Da Momentan das ganze irgendwie so nicht mehr Funktioniert

### Version

v13.0.8 (Commit: 04f2f23+)

### Logfile

```shell
Not Needed
```

### Expected Behavior

Werte "Home/HwRaum/Wasseruhr" 

Homeassistant Auto Discovery:  "homeassistant/sensor/Wasseruhr"

und nicht 

Werte: Home/HwRaum/Wasseruhr
homeassistan Auto-Discovery: homeassistant/sensor/Home/HwRaum/Wasseruhr

### Screenshots

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by henrythasler**
homeassistant needs the MQTT discovery topic according to the following structure:
`<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`
If the main topic is embedded in a nested structure, we just use the last part as node_id. This means a maintopic `home/test/watermeter` is transformed to the discovery topic `homeassistant/sensor/watermeter/...`

fixes #1792

### CODE REVIEW

**Comment by caco3** [comment]
Do I see it right that this change only has an impact on devices which have a `/` in the maintopic?
Or will it break existing systems?

**Comment by caco3** [comment]
And can you also extend the documentation at https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/param-docs/parameter-pages/MQTT/MainTopic.md please?

**Comment by henrythasler** [comment]
> Do I see it right that this change only has an impact on devices which have a `/` in the maintopic? Or will it break existing systems?

It does only impact topics with multiple levels. To make this more clear, I have added a unit-test.

**Comment by henrythasler** [comment]
> And can you also extend the documentation at https://github.com/jomjol/AI-on-the-edge-device/blob/rolling/param-docs/parameter-pages/MQTT/MainTopic.md please?

Done

**Comment by caco3** [comment]
Thanks!

Seems to work well:
grafik

---

grafik

**Pull request merged**
